### ISSUE TITLE
deserialize_any treats integers as f64

### ISSUE THREAD

**Issue by Lukazoid** [ron-rs/ron#100]
The [current implementation](https://github.com/ron-rs/ron/blob/a5a4b2ee21f5be0b07c55844e2689ae8a521da3b/src/de/mod.rs#L124) of `deserialize_any` treats all numeric values as f64. 

This causes issues when using crates such as [serde-value](https://github.com/arcnmx/serde-value) as it will deserialize to the F64 variant preventing it from subsequently being able to be deserialized to an integer field, e.g.:

    #[derive(Deserialize, Serialize)]
    struct Config {
        value: u32
    }

    fn value_deserialize_ron() {
        let serialized = r#"(
            value: 5
        )"#;

        let value = ::ron::de::from_str::<::serde_value::Value>(serialized).unwrap();

        let config = value.deserialize_into::<Config>().expect("failed to deserialize from value");
    }

This fails on the last line with the following error:

> failed to deserialize from value: InvalidType(Float(5.0), "u32")

Both serde yaml:

    fn value_deserialize_yaml() {
        let serialized = r#"
            value: 5
        "#;

        let value = ::serde_yaml::from_str::<::serde_value::Value>(serialized).unwrap();

        let config = value.deserialize_into::<Config>().expect("failed to deserialize from value");
    }

And serde json:

    fn value_deserialize_json() {
        let serialized = r#"{
            "value": 5
        }"#;

        let value = ::serde_json::from_str::<::serde_value::Value>(serialized).unwrap();

        let config = value.deserialize_into::<Config>().expect("failed to deserialize from value");
    }

Are able to handle this case correctly, so I believe the issue is with how Ron parses these numeric values.

**Comment by torkleyy** [comment]
I see. What I could do is parse it as integer if there is no fractional part, but I'm not sure if that's always useful. The problem is that `53` is a valid floating-point number in RON, so it would parse as integer even though you're expecting a floating-point number. Then there's also the problem with very big numbers that don't fit into `u64`.

I'm not sure how json handles all this. Is there maybe an automatic conversion from int to float when deserializing?

**Comment by Lukazoid** [comment]
I think having `53` read as an integer is fine as serde can deserialize to `f32` and `f64` values from all of the integer types (see [here](https://github.com/serde-rs/serde/blob/5efb22ebee128f1ec4a755556230bdd66c3f2026/serde/src/de/impls.rs#L165-L166)).

From [this](https://github.com/serde-rs/json/blob/4e6387f601d6eb54edcbcc0642d9523d4eb6998c/src/de.rs#L307-L309) it appears that serde-json attempts to read as an integer until it grows too large.

**Comment by torkleyy** [comment]
Okay, I'm in favor of splitting `Value::Number` into `Value::Float` and an integer variant. Do we need both signed and unsigned variants?
