### ISSUE TITLE
Clean up configuration API

### ISSUE THREAD

**Issue by Phrohdoh** [ron-rs/ron#105]
I'd like the ability to enable `struct_names` (via `PrettyConfig`) in https://github.com/ron-rs/ron/blob/5efdf123de373ec466b3dbfd0c61a4f6991a0127/src/ser/mod.rs#L34.

**Comment by torkleyy** [comment]
Hey! You can use `Serializer::new` for now.

**Comment by torkleyy** [comment]
I think this is part of a bigger issue, the configuration API could use some clean up.

**Comment by torkleyy** [comment]
I've improved the config in #173, but I'm not quite sure about `struct_names`. The thing is, it can be set independently of a `PrettyConfig`, i.e. it can also be used for non-pretty serialization.

**Comment by j-n-f** [comment]
would there be any reason to not add this to `PrettyConfig` (with default value as `false`)?

I was able to work around this using `Serializer::new` as you described, but as a newbie in Rust it took me a while to work out how to do it (there's a few extra steps involved). Maybe at the very least it would be helpful to have this as example code somewhere in the examples or docs.

**Comment by kvark** [comment]
@j-n-f the reason was outlined by a comment above yours:
>  The thing is, it can be set independently of a `PrettyConfig`, i.e. it can also be used for non-pretty serialization.

**Comment by j-n-f** [comment]
Would a pull request to include this method of doing things in the documentation/examples be helpful?

**Comment by kvark** [comment]
@j-n-f please clarify what "this method" you are referring to?

**Comment by j-n-f** [comment]
@kvark I had to do something like the following (maybe this isn't the best way):

```
// Create a serializer with `struct_names` set to `true`
let mut serializer = ron::ser::Serializer::new(Some(pretty_config), true);
application_struct_instance.serialize(&mut serializer).expect("couldn't serialize");
let serialized = serializer.into_output_string();
```

This is compared to the "easy" way that `ron` provides that would look more like:

```
let serialized = application_struct_instance.to_string_pretty(pretty_config);
```

I think an example named something like `with_struct_names.rs` would be helpful.

**Comment by kvark** [comment]
@torkleyy I'm inclined to suggest that we just don't make this configurable for non-pretty path and skip the struct names. This would mean moving the flag into `PrettyConfig`.

**Comment by torkleyy** [comment]
Yeah, let's do that.
