### ISSUE TITLE
`to_string` produces text that `from_str` does not accept (with tuple variants)

### ISSUE THREAD

**Issue by Phrohdoh** [ron-rs/ron#107]
```
# Cargo.toml
ron = "0.2.1"
```

---

Given the following type:

```rust
pub enum FileOrMem {
    File(String),
    Memory,
}
```

`ser::to_string` produces the following RON:

```
            data: Node (
                location: Location (
                    file_or_mem: File(
                        "foo/bar"
                    ),
                    column: 1,
                    line: 1
                ),
                key: "Player",
                value: None,
                comment: None
            )
```

Which fails deserialization with:

```
Parser(ExpectedString, Position { col: 39, line: 19 })
```

The fix, IME, is to change the text to be inline. But this should be fixed in parsing IMO (what I mean is that this syntax is reasonable and should be accepted).

---

For the sake of completeness this error is not restricted to string literals on a new line.

It also occurs if there is a space between the `(` and `"`.

**Comment by torkleyy** [comment]
Version 0.2.2 is uploaded.

**Comment by Phrohdoh** [comment]
Thanks for the speedy fix, @torkleyy! :tada:
