### ISSUE TITLE
Untagged tuple-like enum variants not deserializing correctly

### ISSUE THREAD

**Issue by ebkalderon** [ron-rs/ron#117]
I am trying to deserialize the following Rust code:

```rust
#[derive(Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct BuildSystem<'m> {
    version: Cow<'m, str>,
    flags: Vec<Flag<'m>>,
}

#[derive(Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(untagged)]
pub enum Flag<'m> {
    Value(Cow<'m, str>),
    If(Cow<'m, str>, Vec<Cow<'m, str>>),
}
```

from the following RON:

```ron
BuildSystem(
    version: "1.0.0",
    flags: [
        "--enable-thing",
        "--enable-other-thing",
        If("some-conditional", ["--enable-third-thing"]),
    ]
)
```

When I attempt to do this, I get the following error:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Parser(ExpectedIdentifier, Position { col: 12, line: 7 })', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

However, when I change the definition of `Flag::If` to be a struct-like enum variant, like so:

```rust
#[derive(Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(untagged)]
pub enum Text<'m> {
    Value(Cow<'m, str>),
    If {
        is_true: Cow<'m, str>,
        then: Vec<Cow<'m, str>>
    },
}
```

and alter the RON accordingly:

```ron
BuildSystem(
    version: "1.0.0",
    flags: [
        "--enable-thing",
        "--enable-other-thing",
        If(is_true: "some-conditional", then: ["--enable-third-thing"]),
    ]
)
```

then everything deserializes correctly. Am I doing something wrong here? It's a tuple-like enum, so there's no reason the parser should be expecting an identifier there. The [enum section](https://github.com/ron-rs/ron/blob/db06c55175ad117eae9cd1c0f73954dc8ed3c9fb/docs/grammar.md#enum) in the formal grammar document seems to agree with me.

**Comment by torkleyy** [comment]
Looks like a bug to me. What does it serialize to?

**Comment by ebkalderon** [comment]
@torkleyy When the `BuildSystem` is constructed manually, it serializes with `ron::ser::to_string()` into:

```ron
(version: "1.0.0", flags: ["--enable-thing","--enable-other-thing", ("some-conditional", ["--enable-third-thing"],),])
```

There doesn't appear to be any issue serializing untagged enums, it seems.

**Comment by ebkalderon** [comment]
Also, I tried deserializing with the following RON to match the serialized output above:

```
BuildSystem(
    version: "1.0.0",
    flags: [
        "--enable-thing",
        "--enable-other-thing",
        ("some-conditional", ["--enable-third-thing"]),
    ]
)
```

I still get the same error as before:

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Parser(ExpectedIdentifier, Position { col: 12, line: 7 })', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by vessd** [comment]
I ran into the same problem
```rust
use serde::{Deserialize, Serialize};
use ron::{de::from_str, ser::to_string};

#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(untagged)]
enum Foo {
    Bar(usize),
}

fn main() -> Result<(), Box<std::error::Error>> {
    let foo_vec = vec![Foo::Bar(0); 5];
    let foo_str = dbg!(to_string(&foo_vec)?);
    dbg!(from_str::<Vec<Foo>>(&foo_str)?);
    Ok(())
}
```
```rust
[src/main.rs:12] to_string(&foo_vec)? = "[0,0,0,0,0,]"
Error: Message("data did not match any variant of untagged enum Foo")
```
with `serde_json` it works fine

**Comment by kvark** [comment]
weird, I'd expect it to write `[Bar(0), Bar(0), Bar(0), Bar(0), Bar(0),]`. We have an [extension](https://github.com/ron-rs/ron/blob/master/docs/extensions.md#unwrap_newtypes) to unwrap those, but it shouldn't be enabled by default.

**Comment by vessd** [comment]
https://github.com/ron-rs/ron/blob/master/src/de/tests.rs#L199
```rust
assert_eq!(from_str::<Untagged>("0").unwrap(), Untagged::U8(0));
```
it doesn't work

**Comment by vessd** [comment]
@kvark serialization is fine, untagged enum should work this way

**Comment by kvark** [comment]
Oops, I see the `#[serde(untagged)]` now, sorry :)

**Comment by torkleyy** [comment]
Ah, I think that's because `deserialize_any` does not generate integers AFAIK.

**Comment by vessd** [comment]
@torkleyy is it difficult to fix?
maybe you can use [Number](https://github.com/serde-rs/json/blob/master/src/number.rs) from `serde_json`?
