### ISSUE TITLE
Generalized typeless deserialization

### ISSUE THREAD

**Issue by Xaeroxe** [ron-rs/ron#119]
In serde_json you have the [`Value`](https://docs.serde.rs/serde_json/enum.Value.html) type which allows the end user to deserialize a value without knowing the underlying type.

This can be useful because for some use cases (such as the Amethyst prefab system) we want to be able to write code to deserialize a value and walk it at run time, in order to determine what we're looking at and what we should do with it.

I'd like ron to offer something similar.

**Comment by Xaeroxe** [comment]
cc @Rhuagh

**Comment by kvark** [comment]
@Xaeroxe I believe we already [have that](https://github.com/ron-rs/ron/blob/366ed9db18d2c301ac9d7a12697a28ab3f95858a/src/value.rs#L48) thanks to @torkleyy

**Comment by Xaeroxe** [comment]
Oh doi, I just found the value module.  Thanks!
