### ISSUE TITLE
Externally, internally, adjacently and un-tagged enums

### ISSUE THREAD

**Issue by torkleyy** [ron-rs/ron#123]
All of those need to be properly tested, I don't think they are working currently. Behavior wrt. `Value` needs to be documented.

Also see: https://serde.rs/enum-representations.html

**Comment by Boscop** [comment]
@torkleyy I just ran into this, a normal enum like this is serialized as `()`:
```
#[derive(Serialize, Deserialize)]
pub enum Foo {
	A,
	B,
	C,
}
Any idea when enums will be supported?

**Comment by kvark** [comment]
@Boscop enums in general are (of course!) supported.
I just tried to add your enum to the `encode.rs` example:
```diff
diff --git a/examples/encode.rs b/examples/encode.rs
index 3d3dc25..bf3b1e1 100644
--- a/examples/encode.rs
+++ b/examples/encode.rs
@@ -10,6 +10,7 @@ struct Config {
     nested: Nested,
     var: Variant,
     array: Vec<()>,
+    foo: Foo,
 }
 
 #[derive(Serialize)]
@@ -26,6 +27,13 @@ struct Nested {
     b: char,
 }
 
+#[derive(Serialize)]
+enum Foo {
+    A,
+    B,
+    C,
+}
+
 fn main() {
     let data = Config {
         float: (2.18, -1.1),
@@ -37,6 +45,7 @@ fn main() {
         },
         var: Variant::A(!0, ""),
         array: vec![(); 3],
+        foo: Foo::C,
     };
 
     let pretty = PrettyConfig::new()
```
And it serializes just fine:
```
(
    float: (2.18,-1.1,),
    tuple: ((),false,),
    map: {1:'2',3:'5',0:'1',8:'1',},
    nested: (a:"Hello from \"RON\"",b:'b',),
    var: A(255,"",),
    array: [(),(),(),],
    foo: C,
)
```

This issue is about funky custom-configured enums that Serde supports, not regular stuff.

**Comment by Boscop** [comment]
@kvark Hm, but for me it serialized it as `()`, any idea why?

**Comment by kvark** [comment]
@Boscop you are likely talking about a different issue. Could you file one, provide the repro steps, and we'll go from there?

**Comment by OvermindDL1** [comment]
Might be related to this, but I've tried each of the 3 enum types.  Basically I have an array of an enum, and I'm trying to get something like this:
```ron
[
    DrawSprite( sprite_name: "blah", rect: Rect(x: 1.0, y: 2.0, w: 3.0, h: 4.0) ),
]
```
But it seems the best I can do is with 'external' serde enum's, to get:
```ron
[
    {"DrawSprite": ( sprite_name: "blah", rect: (x: 1.0, y: 2.0, w: 3.0, h: 4.0) )},
]
```
Is it planned to have a way to use the enum head names as the top level 'object' like in the first code-fence?

**Comment by OvermindDL1** [comment]
And for note, trying the prior example just has it report `1: 3:5: Expected map`, I'm unsure why it needs a map for a single enum value per array cell though...

**Comment by OvermindDL1** [comment]
Is this supposed to be closed?

**Comment by torkleyy** [comment]
I don't think this is still an issue @OvermindDL1
