### ISSUE TITLE
Feature request: preserve order in value

### ISSUE THREAD

**Issue by matklad** [ron-rs/ron#129]
Currently, value is based on `BTree` map, which loses the original order of ron document. I think it makes sense to add an option to preserve order. I'd even say that if ron's primary purpose is to be a human-editable format, then order should be preserved by default.  https://crates.io/crates/indexmap might come in handy do actually implement this. 

Here's my specific use-case for ordering: I [use ron](https://github.com/matklad/libsyntax2/blob/de02d2891ec7f7b295e33887d49de954f677387a/crates/libsyntax2/src/grammar.ron) to generate the AST for Rust. As such, I group related things, like types or expressions, together, and ideally I'd love to see the same order in the generated code. Alas, as I use [a map](https://github.com/matklad/libsyntax2/blob/de02d2891ec7f7b295e33887d49de954f677387a/crates/libsyntax2/src/grammar.ron#L218-L235) for some part of my input, it doesn't work. I can swtich to a list of pairs for this case, but a mapping makes more sense.

**Comment by kvark** [comment]
@matklad this sounds very reasonable

**Comment by VermillionAzure** [comment]
If support is added for an ordered map parsing mode, how would you like this functionality to be enabled? A macro? An object-format flag? One frustrating thing that could occur now is that the serialized format doesn't show whether it is meant to be parsed in "preserved order mode" or "ordered key mode." This could be problematic if we ever want to provide syntax highlighting support for RON. Should we consider schemas for this?

**Comment by kvark** [comment]
@VermillionAzure as I understand this issue, it's not about parsing, it's about serialization only. The parser should work regardless, and no new extensions are needed. I think it can just be an option of the serializer (or a compile feature that enables it and adds dependency on `indexmap`).

**Comment by torkleyy** [comment]
@VermillionAzure Are you still interested in fixing this issue?

**Comment by lykhouzov** [comment]
Hello, does this will be implemented. I am not sure if i have the same issue, but when I Deserizlise, i do not have the same structure order.
I am using hashmap as
```
(
tasks: {
    "debug message": Dbg(
      msg: "test message. some text after it."
    ),
    "shell command": Shell(
      command: "ls",
      args: Some([
        "-l",
        "-h",
      ]),
      ch_dir: Some("/")
    ),
}
)
```
and it does not preserve order of it, so that sometimes `shell command` goes first.

**Comment by kvark** [comment]
@lykhouzov if your tasks is a `HashMap`, then yes, you are hitting the same issue.
I don't know if you need to have a hashmap there though, might easily do `tasks: [...]` as a list.

**Comment by lykhouzov** [comment]
Hi, @kvark. So yes, it is `HashMap`.
I already was thinking about use Vec instead, but this construction looks more readable for me.
Porbably i will convert it to something like following if this issue is not gonna be fixed
```
[
    ("debug message", Dbg(
      msg: "test message. some text after it."
    )),
    ("shell command",Shell(
      command: "ls",
      args: Some([
        "-l",
        "-h",
      ]),
      ch_dir: Some("/")
    ))
]
```
or maybe move a name of a task to task itself.
Thanks

**Comment by torkleyy** [comment]
@lykhouzov You could also just replace the `HashMap` type by [`IndexMap`](https://docs.rs/indexmap/1.0.2/indexmap/map/struct.IndexMap.html).

**Comment by torkleyy** [comment]
Blocked by https://github.com/bluss/indexmap/issues/91
