### ISSUE TITLE
Adding unnecessary fields doesn't trigger an error.

### ISSUE THREAD

**Issue by jojolepro** [ron-rs/ron#133]
This actually creates hard to track bug when what we want to load is actually missing fields, but the file we load looks fine and has that field and there is no error on load.

**Comment by torkleyy** [comment]
That's not a RON issue. Serde does give you a warning, we can't do more about this.

**Comment by jojolepro** [comment]
If there's a warning by serde, then its okay. I opened the issue for someone else. Said person probably forgot to check the log :)
thanks
