### ISSUE TITLE
Underscores in numerals

### ISSUE THREAD

**Issue by alberdingk-thijm** [ron-rs/ron#134]
This is a pretty straightforward feature request for `_` characters in numbers in ron, similar to how they are allowed in Rust. I'm really just looking to make my files with big numbers slightly more readable.

To clarify, I want to be able to write this:
```
foo: 123_456_789.0
```

Currently, ron gives a `Parser(ExpectedArrayEnd, Position { ... })` error at the underscore.

**Comment by torkleyy** [comment]
I'm just seeing that your example uses a floating point number. In my PR I
only implemented it for integers.
