### ISSUE TITLE
Implement ron! macro

### ISSUE THREAD

**Issue by matklad** [ron-rs/ron#143]
See https://docs.serde.rs/serde_json/macro.json.html for the `json!` equivalent.

**Comment by CAD97** [comment]
I'm experimenting with [a reimplementation](https://github.com/CAD97/ron/tree/rewrite) to try and address some of the outstanding issues that are made hard to address because of the current implementation structure, and to bring ron more inline with how e.g. serde_json is implemented, to hopefully make it easier to maintain going forward.

Anyway, the reason I say this here is that said experimental branch now has [a working `ron!` macro](https://github.com/CAD97/ron/blob/2592e4802444553304ca23734d8ae7ea8f9c2717/src/macros.rs#L289-L316) I wanted to share off.

```rust
    let ron = ron! {
        GameConfig( // optional struct name
            window_size: (800, 600),
            window_title: "PAC-MAN",
            fullscreen: false,

            mouse_sensitivity: 1.4,
            key_bindings: {
                "up": Up,
                "down": Down,
                "left": Left,
                "right": Right,

                // Uncomment to enable WASD controls
                /*
                "W": Up,
                "A": Down,
                "S": Left,
                "D": Right,
                */
            },

            difficulty_options: (
                start_difficulty: Easy,
                adaptive: false,
            ),
        )
    };
    dbg!(&ron);
    println!("{}", crate::to_string(&ron).unwrap());
```

output:

```
[src\macros.rs:317] &ron = GameConfig {
    window_size: (
        +800,
        +600,
    ),
    window_title: "PAC-MAN",
    fullscreen: false,
    mouse_sensitivity: 1.4,
    key_bindings: {
        "up": Up,
        "down": Down,
        "left": Left,
        "right": Right,
    },
    difficulty_options: _ {
        start_difficulty: Easy,
        adaptive: false,
    },
}
GameConfig(
    window_size: (
        +800,
        +600
    ),
    window_title: "PAC-MAN",
    fullscreen: false,
    mouse_sensitivity: 1.4,
    key_bindings: {
        "up": Up,
        "down": Down,
        "left": Left,
        "right": Right
    },
    difficulty_options: (
        start_difficulty: Easy,
        adaptive: false
    )
)
```

**Comment by rollo-b2c2** [comment]
Hey are there any plans to revive this?

This is super useful, particularly for tests where I have quite deep data structures.

Typical workflow.

1. serialize test output to ron
2. check it over
3. copy into test
4. assert that output matches serialized output

With this I can do some more advanced things.

**Comment by juntyr** [comment]
This issue predates my work on ron, thank you for bringing it to my attention!

I think it would be a good idea to bring it back, but I cannot devote the time to implement it myself. Feel free to open a PR with an implementation :)
