### ISSUE TITLE
Control integer representations

### ISSUE THREAD

**Issue by kvark** [ron-rs/ron#144]
It would be good to be able to say that a particular integer needs to be serialized in hex, for example. On first approximation, this doesn't appear to be possible through serde attributes, since serde doesn't care about how integers are parsed.

**Comment by torkleyy** [comment]
Can you control the definition of the struct? I'd just use a custom path:

```rust
pub struct MyStruct {
    #[serde(with = "hex")]
    flags: usize,
}

mod hex {
    // pseudo code
    fn serialize<S>(flags: &usize, ser: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let flags = flags.to_hex_string();
        ser.serialize_str(&flags)
    }

    // fn deserialize
}
```

**Comment by torkleyy** [comment]
@kvark Does this work for your use case?

**Comment by kvark** [comment]
Trouble is that in WebRender the same structure may need to be serialized with both bincode and RON. And I only want RON to be showing the hex representation, of course.

**Comment by torkleyy** [comment]
Okay, I understand. So you want to set the representation of all integers globally?

**Comment by kvark** [comment]
@torkleyy nope, not all integers, just a particular field of a particular struct.

**Comment by torkleyy** [comment]
Okay. So given that werde doesn’t support that, the only option I see would be to configure overrides for the serializer. Something like

```rust
serializer.for_field(“flags”, Repr::Hex);
```

which... seems very special case-y.

**Comment by kvark** [comment]
That's an interesting approach, and while inconvenient, it's certainly at least an option for us to proceed. I'd say let's expose this in some way.

**Comment by CAD97** [comment]
The serialized structure can also look at `serializer.is_human_readable()` and serialize differently depending on that.
