### ISSUE TITLE
raw strings in rust are context-sensitive

### ISSUE THREAD

**Issue by Gankro** [ron-rs/ron#167]
The grammar docs note:

> Note: Raw strings start with an r, followed by n # and a quotation mark ". They may contain any characters or escapes (except the end sequence). A raw string ends with a quotation mark ("), followed by n #.
>
> I don't know any sane way to write this out in EBNF, if you do, let me know.

It can't be written in EBNF because the syntax of EBNF is for expressing context-free grammars, while raw strings are context-sensitive:

https://github.com/rust-lang/rust/blob/master/src/grammar/raw-string-literal-ambiguity.md

(As a general rule, context-free languages can only compare two numbers destructively, so comparing 3 numbers doesn't work)

**Comment by torkleyy** [comment]
Thanks @Gankro, fixed this in #171.
