### ISSUE TITLE
[Editor Request] Support for Atom editor

### ISSUE THREAD

**Issue by olvyko** [ron-rs/ron#168]
The [Atom Editor](https://atom.io) currently supports Rust language. 
Even, at the moment, the highlighting and understanding of the Rust code 
in Atom is [better](https://github.blog/2018-10-31-atoms-new-parsing-system/) than in other editors.
Are there any plans for adding support for RON for this editor?

**Comment by torkleyy** [comment]
No plans directly, no. But if somebody creates a plugin, I'd love to add a link to the README :)

**Comment by olvyko** [comment]
I made language package for Atom.
https://github.com/olvyko/language-ron
https://atom.io/packages/language-ron
