### ISSUE TITLE
Depth limit seems to be off by one

### ISSUE THREAD

**Issue by torkleyy** [ron-rs/ron#174]
Currently, a depth limit of `1` means that nothing gets indented (same for `0`). That seems wrong, as the limit should be the (inclusive) maximum depth.

This can be fixed by changing the `pretty.indent < config.ident` to a `<=` check.

@kvark Do you agree this is a bug?

**Comment by kvark** [comment]
yeah, let's fix this

**Comment by Boscop** [comment]
Bump :)

**Comment by kvark** [comment]
PR's welcome!
