### ISSUE TITLE
Current `Serializer` is hard to maintain

### ISSUE THREAD

**Issue by torkleyy** [ron-rs/ron#175]
## The problem

The current serializer provides all kind of config parameters, but as it is now, it became hard to maintain.
Many things are special cased, and code is duplicated across tuples / enums / sequences / maps.

Additionally, we're lacking tests for pretty serialization.

## How to fix this

We need to build an abstraction for comma separated values, which removes the duplication we have now.

Once that's done, special cases should be easier to identify.

**Comment by torkleyy** [comment]
This is still a problem, although we have more tests now thanks to @MomoLangenstein which should make refactoring easier.

**Comment by kvark** [comment]
weird that GH actions bot closes this, even thought there is a comment?

**Comment by juntyr** [comment]
I think that #206 fixed the code duplication issue and #488 finally pushed the serialising code to 100% code coverage
