### ISSUE TITLE
Add code coverage badge

### ISSUE THREAD

**Issue by torkleyy** [ron-rs/ron#176]
We should measure code coverage by CI and add a badge to the repo, goal being to increase have RON fully covered by tests.

**Comment by torkleyy** [comment]
I guess we could look into this. I think code coverage by itself is a stupid goal because it doesn't require any useful assertions, but it can give some indication that tests are in place...

**Comment by kvark** [comment]
damn bot. Can we disable it?

**Comment by MomoLangenstein** [comment]
@torkleyy I've tested this out a bit and you can see how it might work in https://github.com/MomoLangenstein/ron/pull/2. If you set up `ron` on the code coverage portal of your choice (I've used codecov before), especially any env secrets, I could create the PR to merge the workflow, and you could add the badge to the `README`.

**Comment by MomoLangenstein** [comment]
The badge could look like this: [![codecov](https://codecov.io/gh/MomoLangenstein/ron/branch/codecov/graph/badge.svg?token=DM0L3IA0I2)](https://codecov.io/gh/MomoLangenstein/ron) or [![codecov](https://img.shields.io/codecov/c/github/MomoLangenstein/ron/codecov?token=DM0L3IA0I2)](https://codecov.io/gh/MomoLangenstein/ron) (the latter doesn't seem to like displaying non-main branch coverage info)
