### ISSUE TITLE
Feature request: Fix missing fields with default

### ISSUE THREAD

**Issue by timokoesters** [ron-rs/ron#179]
When the struct defined in the rust code changes, but the existing ron file is at the old version, it's no longer readable at all.

I'm trying to use ron for saving keybinds and other settings for a game, but in the current state new versions of the config are not compatible with old ones at all.

What I imagine is a method called from_reader_fixed() which deserializes a .ron file, removes unnecessary options and inserts a default for missing options.

**Comment by torkleyy** [comment]
You can already use Serde to achieve that. Just put a `#[serde(default)]` on the field, and it will use the default value when it's missing.

As for old ones, it will simply ignore them.

If you need more complex handling, you can also just create a compatibility struct / `ron::Value` to get additional information.

**Comment by timokoesters** [comment]
What about fields with the same name but a different type? Will serde reset them to the default as well?

**Comment by torkleyy** [comment]
No, in that case it would fail.

**Comment by Boscop** [comment]
@timokoesters I guess this issue can be closed. 
Btw, for converting types during (de)serialization I wrote some macros:
```rust
/// serializes a type as a different repr type that it can be converted Into and From
#[macro_export]
macro_rules! serde_as {
	($m:ident, $t:ty, $r:ty) => {
		pub mod $m {
			use super::*;
			use serde::{Deserialize, Deserializer, Serialize, Serializer};

			pub fn serialize<S: Serializer>(x: &$t, serializer: S) -> Result<S::Ok, S::Error> {
				let y: $r = (*x).into();
				y.serialize(serializer)
			}

			pub fn deserialize<'de, D: Deserializer<'de>>(deserializer: D) -> Result<$t, D::Error> {
				let y: $r = Deserialize::deserialize(deserializer)?;
				Ok(y.into())
			}
		}
	};
}

/// serializes a type as a different repr type using the given conversion functions
#[macro_export]
macro_rules! serde_conv {
	($m:ident, $t:ty, $ser:expr, $de:expr) => {
		pub mod $m {
			use super::*;
			use serde::{Deserialize, Deserializer, Serialize, Serializer};

			pub fn serialize<S: Serializer>(x: &$t, serializer: S) -> Result<S::Ok, S::Error> {
				let y = $ser(*x);
				y.serialize(serializer)
			}

			pub fn deserialize<'de, D: Deserializer<'de>>(deserializer: D) -> Result<$t, D::Error> {
				let y = Deserialize::deserialize(deserializer)?;
				Ok($de(y))
			}
		}
	};
}
```

[Example of using `serde_conv`.](https://github.com/Boscop/yew-geolocation/blob/63dec0618393eda60becf8978a212c854f0ed5be/src/lib.rs#L24-L29)
Example of using `serde_as`: 
```rust
serde_as!(serde_col, RGB<f32>, (f32, f32, f32));
pub struct Col(#[serde(with = "serde_col")] pub RGB<f32>);
```
When your rust types change and you want to load data from before, you need to write a migration to upgrade the data to the next version (and from that one to the next, until you arrive at the latest). The easiest way to do this would be to include `version` int field as first field in your top-level struct, and a ron `Value` to deserialize the rest into, then run the migrations like this:
```rust
struct Doc {
	version: u32,
	data: Value,
}
type CurrentFileFormat = FileFormat17; // == whatever the latest version is. Migrations use the structs of earlier versions. You need to keep all of them in your code
// ..
let Doc { version, data } = ron::de::from_reader(..)?;
for migration in migrations[version..] {
	data = migration.migrate(data); // takes a ron Value, deserializes it into FileFormatN and returns a ron Value in the next version (FileFormat(N+1))
}
let data = data.into_rust::<CurrentFileFormat>()?;
```
Then you have a clean & linear file format upgrader, e.g. like Visual Studio project file upgrader.

**Comment by srid** [comment]
Perhaps this migration method is worth mentioning in the README or a FAQ?
