### ISSUE TITLE
Add Documentation for new RON IntelliJ Plugin

### ISSUE THREAD

**Issue by vultix** [ron-rs/ron#181]
This is a heads up that there is a new IntelliJ Plugin for RON that supports importing rust types, type validation, and completion.  You can check it out [right here](https://vultix.github.io/intellij-ron-plugin/).

It would be helpful for RON users if this repository had a link in the readme to the plugin so that they know there is advanced tooling available.

Thanks!

**Comment by kvark** [comment]
we totally love you work, just so you know :)

**Comment by OvermindDL1** [comment]
This plugin isn't working as attempting to install it states that I need to purchase a license...?  o.O

Using IntelliJ Ultimate.

**Comment by kvark** [comment]
just because it requires payment doesn't mean that it doesn't work :)
