### ISSUE TITLE
Unified Error type

### ISSUE THREAD

**Issue by Mathspy** [ron-rs/ron#183]
Would it make sense to follow the pattern introduced by other `serde` libraries of exposing a top-level Error type that unifies the error types possible within the crate?
Some references:
[JSON](https://docs.serde.rs/serde_json/struct.Error.html)
[XML](https://docs.rs/serde-xml-rs/0.3.1/serde_xml_rs/struct.Error.html)
[YAML](https://docs.serde.rs/serde_yaml/struct.Error.html)
[bincode](https://docs.rs/bincode/1.1.4/bincode/type.Error.html)

If people think this is a desirable feature I'd like to submit a PR

**Comment by Evrey** [comment]
I like the split, but having an `impl From<…>` unifying one for convenience might indeed be nice to have. And given the number of example crates using unifying errors, there might be enough desire to do this here as well.

What I like about such splits is that one can exhaustively match on error cases that are possible to occur, there are no impossible ones.

Disclaimer: Am no `ron` user. Just dropping my opinion on good API design. =)

**Comment by kvark** [comment]
@Mathspy looks like all these crates use different representation of `Error`, so it's not clear to me how the unified one would look like.

Another small concern I have is - who would benefit from these types being shared? It's not very likely that many different formats would be used in the same app, and they'd need a place where the errors are merged.

**Comment by OvermindDL1** [comment]
> What I like about such splits is that one can exhaustively match on error cases that are possible to occur, there are no impossible ones.

This is precisely why Rust's Enum's should have OCaml's Polymorphic Variants support.  OCaml Variants are like Rust Enum's as they are now, but OCaml's Polymorphic Variants allow for a syntax to specific what specific head with what specific types could possibly be returned from (or accepted into) a function.  This would allow you to specify all possible error types and all handling of it through functions is known for what could possibly come out, so you don't have to worry about match's being incomplete or 'too' busy without putting in a default case (I really really hate default cases, it makes adding more heads invisible in that location, which is really bad for refactoring and maintainability).

It would be a fairly simple extension of Rust's Enum system type, maybe someday...

**Comment by Mathspy** [comment]
@kvark my idea personally was a simple enum with two variants SerializeError/DeserializeError, it's not much of a huge enchantment besides a simple convenience-y instead of people having to create that enum for each of their applications that uses `ron` (if they care about both serializing and deserializing in same application)

**Comment by kvark** [comment]
Oh wait, so you want an enum over the types for ron/json/other? I don't know if this is useful, but it wouldn't be a part of the `ron` crate, if I understand your idea correctly.

**Comment by Mathspy** [comment]
Sorry for not being clear!
This is basically my idea (and something I already implemented in my code using RON):
```rust
pub enum RonError {
    Deserialize(ron::de::Error),
    Serialize(ron::ser::Error),
}
```
Though there is definitely better ways to do this (P.S: I am relatively new to Rust) so I am not attached to the idea, but simply proposing an enhancement to think about (others probably can come up with better designs than this)

**Comment by kvark** [comment]
Oh, so you are proposing to expose this enum to users, but perhaps not even return it explicitly from any function? @torkleyy do you have a stance on this?

**Comment by torkleyy** [comment]
Yeah, that‘s sensible. Should be sufficient to add this to lib.rs, together with the trait implementations.
