### ISSUE TITLE
Testing for valid ron files

### ISSUE THREAD

**Issue by fkarg** [ron-rs/ron#192]
It would be pretty awesome if you could provide an example as to how to test the validity of ron files with `cargo test` tests. With that, at least the 'tested' files can be guaranteed to be valid.

I imagine it to look something akin to this:

```rust
#[derive(Default)]
struct Point {
    x: f32,
    y: f32,
}


#[cfg(test)]
mod tests {
    #[test]
    fn load_ron_point() {

        let point: Option<Point> = load::<Point>("path/to/file.ron");
        assert_eq!(point.is_some(), true);

    }
}
```

And the test failing if for some reason the ron-file from the given path is no syntactically correct Point-type ron file.

**Comment by kvark** [comment]
Isn't this covered by [decode_file](https://github.com/ron-rs/ron/blob/master/examples/decode_file.rs) example?
