### ISSUE TITLE
How to serialize to a Vec<u8> buffer?

### ISSUE THREAD

**Issue by ChenZhongPu** [ron-rs/ron#194]
An exercise from [pingcap](https://github.com/pingcap/talent-plan/blob/master/rust/building-blocks/bb-2.md) requires to serialize to a `Vec<u8>`  buffer using `ron`. But, it seems that the `String` is the only output option. 

Any one can help me figure this out?

**Comment by kvark** [comment]
The point of RON is to be human readable and modify-able. Working with `Vec<u8>` is not that.
One option would be to use [String::as_bytes](https://doc.rust-lang.org/stable/std/string/struct.String.html#method.as_bytes). Another - to use a different serialization format that is better suited for raw bytes, like [bincode](https://github.com/servo/bincode).

**Comment by torkleyy** [comment]
@ChenZhongPu `String` is just a `Vec<u8>` internally, so you can just use https://doc.rust-lang.org/std/string/struct.String.html#method.into_bytes to consume the bytes.

**Comment by ChenZhongPu** [comment]
I see.  But I still do not know why this exercise ([pingcap](https://github.com/pingcap/talent-plan/blob/master/rust/building-blocks/bb-2.md)) requires me to serialize it to a `String` and convert it `Vec`, and then convert it back. 

> Do the same as above, except this time, instead of serializing to a `File`, serialize to a `Vec<u8>` buffer, and after that try using `RON` instead of `JSON` as the format. Are there any differences in serialization to a `Vec` instead of a File? What about in using the `RON` crate vs the `JSON` crate?

> Convert the `Vec<u8>` to `String` with `str::from_utf8`, unwrapping the result, then print that serialized string representation to see what `Move` looks like serialized to `RON`.

**Comment by torkleyy** [comment]
Hmm, I don't know either.

**Comment by k0Iry** [comment]
> I see. But I still do not know why this exercise ([pingcap](https://github.com/pingcap/talent-plan/blob/master/rust/building-blocks/bb-2.md)) requires me to serialize it to a `String` and convert it `Vec`, and then convert it back.

Yeah, this just looks stupid... lol

**Comment by juntyr** [comment]
Can you use `ser::to_writer` and pass a `Vec<u8>` as a writer

**Comment by k0Iry** [comment]
> Can you use `ser::to_writer` and pass a `Vec<u8>` as a writer

`Vec<u8>` does implement Write trait, but also `to_writer` seems to consume the vector, what if I want to check the content of this Vector, I probably should pass `&mut [u8]` instead right?
```
let a = Move::Right;
let mut v: Vec<u8> = vec![0; 10];
let slice = v.as_mut_slice();
ron::ser::to_writer(slice, &a).unwrap();
println!("v = {:?}", v);
```

From which I got `v = [82, 105, 103, 104, 116, 0, 0, 0, 0, 0]`
