### ISSUE TITLE
PrettyConfig::new() not found when referenced by crate

### ISSUE THREAD

**Issue by peter-scholtens** [ron-rs/ron#198]
Although the examples in the RON crate itself work fine, the example **encode.rs** fails if I create my own project which uses RON. The compiler cannot find the `new()` function. E.g:
`let pretty = PrettyConfig::new()`
^^^ function or associated item not found in `ron::ser::PrettyConfig`

I did include the following dependencies in Cargo.toml :
`ron = "0.5.1"`
`serde = { version = "1", features = ["serde_derive"] }`
`serde_json = "1"`
And copied the file **../ron/examples/decode_file.rs** to the **main.rs** of my project. All other three examples works, but this ones fails. What is wrong?

**Comment by kvark** [comment]
The examples in `master` are written against the code of `master`. If you need example code for "0.5.1" version, you can find them in the relevant source cached by the docs.rs: https://docs.rs/crate/ron/0.5.1/source/examples/encode.rs

**Comment by peter-scholtens** [comment]
Okay, solved.
