### ISSUE TITLE
Clarify multiline comments support

### ISSUE THREAD

**Issue by afilip1** [ron-rs/ron#201]
Hi, [ronfmt](http://github.com/afilip1/ronfmt) author here. I'm currently in the process of implementing comment formatting support, and I wanted to confirm the status of multiline comment support in RON. It seems like it has been implemented (#98), but the spec has not been updated. Is it stable to target, or should I hold off on that? Cheers.

**Comment by kvark** [comment]
I'd say it's safe to target. @torkleyy please correct otherwise.

**Comment by torkleyy** [comment]
Ah yes, seems I forgot to update the spec.
