### ISSUE TITLE
Clippy + rustfmt project

### ISSUE THREAD

**Issue by elrnv** [ron-rs/ron#211]
Should this project run through clippy and rustfmt checks in CI.

Given that there is an explicit rustfmt.toml it is surprising that the diff is currently so large when running rustfmt on the project.

**Comment by elrnv** [comment]
To add, I would be happy to submit a PR for this.

**Comment by kvark** [comment]
I think we should take this opportunity and switch to rustfmt stable, removing all the options that are nightly-only.
Clippy would be great! but perhaps not if it's going to block the PRs because of warnings.

**Comment by elrnv** [comment]
This is resolved by #215 and #214.
