### ISSUE TITLE
Need a new release

### ISSUE THREAD

**Issue by CAD97** [ron-rs/ron#218]
Specifically, `unwrap_newtypes` would be great to have for serialization as well as deserialization.

This is especially relevant because serde recommends the "unwrapped" newtype representation, and ron is the odd one out in considering them semantically meaningful.

**Comment by CAD97** [comment]
..and I went to look at implementing this, and it's already implemented.

Could we get a new release with that code?

**Comment by CAD97** [comment]
Sniffing: https://github.com/ron-rs/ron/pull/182, 10 months ago added this.

**Comment by kvark** [comment]
Based on your investigation in https://github.com/ron-rs/ron/pull/196#issuecomment-622537089, I created a "v0.5" branch. You can make a PR that back-ports all the non-breaking changes you'd like to see in 0.5.2 towards this branch, and bump the patch version. I'll be happy to review the changes (for breakage) and publish.

**Comment by bpfoley** [comment]
I'd also like to see a release that depends on base64 0.12 (which is a compatibility change, and is implemented on master). Would it be worth jumping straight to 0.6?

**Comment by CAD97** [comment]
Yeah, this issue is not specifically about a new 0.5 release but just a release with the new progress since 0.5.1

**Comment by CAD97** [comment]
See also #196 which has some discussion about preparing for a 0.6.

**Comment by Boscop** [comment]
Any update on this? I'm also interested in `unwrap_newtypes` for serialization.

**Comment by kvark** [comment]
I believe this has landed in 0.6

**Comment by Boscop** [comment]
@kvark But unwrap_newtypes is not working for serialization. The serializer doesn't even check the flag.

**Comment by Boscop** [comment]
https://docs.rs/ron/0.6.2/src/ron/ser/mod.rs.html#240

**Comment by kvark** [comment]
This issue is for the breaking 0.6 release, and it was done.

So the feature landed for deserializer only?
Filed https://github.com/ron-rs/ron/issues/284 to follow-up.
