### ISSUE TITLE
Auto Some-wrapping of Option<T> config values

### ISSUE THREAD

**Issue by Boscop** [ron-rs/ron#231]
E.g. if the Config struct contains a `foo: Option<i32>`, a value of `foo: 42` in the config should be accepted, and converted to `Some(42)` automatically, instead of failing to deserialize.

**Comment by kvark** [comment]
I believe this is what the newtype extension does - #72

**Comment by Boscop** [comment]
@kvark I don't mean newtype wrapping, I meant if my struct has a field `#[serde(default)] foo: Option<i32>` then currently the ron file has to contains `foo: Some(42)`, even though if I want `None`, I just omit the field.
With `serde_json`, writing `foo: 42` works, too (becomes `Some(42)`).

But maybe that's not a good behavior because of ambiguity in cases like `Option<Option<T>>`..

**Comment by kvark** [comment]
Ah sorry, you are totally right, discard my previous comment 😅

**Comment by jonasbb** [comment]
@Boscop If you are willing to use third-party crates you could try [`serde_with::rust::unwrap_or_skip`](https://docs.rs/serde_with/1.6.0/serde_with/rust/unwrap_or_skip/index.html). It was written for RON. It only requires some attributes on the optional fields: `#[serde(default, skip_serializing_if = "Option::is_none", with = "::serde_with::rust::unwrap_or_skip")]`

**Comment by Boscop** [comment]
@jonasbb Thanks. (Btw, this issue was about deserializing `T` into `Option<T>` which is now supported via the `implicit_some` extension.)
But yes, I also often want the reverse: Skipping `None` during serialization (and serializing only `val` instead of `Some(val)` in that case.
So the point of `with = "::serde_with::rust::unwrap_or_skip"` instead of just `#[serde(default, skip_serializing_if = "Option::is_none")]` is that `Some(val)` will serialize as just `val`, right?

**Comment by jonasbb** [comment]
@Boscop The listed combination of attributes works for serialization and deserialization. This allows you to round trip the data. It also allows you to omit the `Some(_)` part without explicitly listing it as an extension.
I didn't know about the extensions yet, I should check how `implicit_some` interacts with `serde_with::rust::unwrap_or_skip`.

>  So the point of `with = "::serde_with::rust::unwrap_or_skip"` instead of just `#[serde(default, skip_serializing_if = "Option::is_none")]` is that `Some(val)` will serialize as just `val`, right?

Yes, exactly. This then allows you to also serialize these documents.

**Comment by Boscop** [comment]
> It also allows you to omit the Some(_) part without explicitly listing it as an extension.

That's a great advantage, the extension line confuses people who come from JSON.
I wish I could also enable the `unwrap_newtypes` extension statically (https://github.com/ron-rs/ron/issues/281) so that it also works when serializing (https://github.com/ron-rs/ron/issues/284).
