### ISSUE TITLE
Support u128 and i128

### ISSUE THREAD

**Issue by Kixiron** [ron-rs/ron#233]
Serde provides an already-implemented method for `u128` and `i128` that just returns an error (See [`Serialize`](https://docs.rs/serde/1.0.110/src/serde/ser/mod.rs.html#621) and [`Deserialize`](https://docs.rs/serde/1.0.110/src/serde/de/mod.rs.html#987)), which makes it impossible to represent Rust code that involves `u128`s or `i128`

**Comment by kvark** [comment]
This was merged in #219 just not published yet. See #196 about the release preparations. I'll get this going now.
