### ISSUE TITLE
Fix raw string grammar

### ISSUE THREAD

**Issue by Koxiaet** [ron-rs/ron#235]
In grammar.md, raw strings are defined as:

```ebnf
string_raw = ("r#", string_raw, "#") | "\"", { unicode_non_greedy }, "\"";
```

This is incorrect, as it doesn't allow things like `r##"string"##`. It should say:

```ebnf
string_raw = "r" string_raw_content;
string_raw_content = ("#", string_raw_content, "#") | "\"", { unicode_non_greedy }, "\"";
```

This is still incorrect as raw strings can't be defined in EBNF, but it is at least more accurate.

**Comment by kvark** [comment]
Can you have arbitrary number of "#" in there? The new grammar would allow `r###"string"###` too

**Comment by Koxiaet** [comment]
@kvark Yes, from grammar.md:

> Note: Raw strings start with an r, followed by n # and a quotation mark
". They may contain any characters or escapes (except the end sequence).
A raw string ends with a quotation mark ("), followed by n #.

n can be any number (including 0)

**Comment by kvark** [comment]
What's the use case for putting more than one "#"? It sounds to me that we could just change the wording in this document to say there is only one "#" instead of changing the logic.

**Comment by Koxiaet** [comment]
@kvark Ron itself already supports any number of hashes, it's just that grammar that's wrong.

**Comment by kvark** [comment]
Ah ok, thank you for clarification! Want to make a PR to fix it?
