### ISSUE TITLE
Documentation says arrays use square brackets, but they actually use parentheses

### ISSUE THREAD

**Issue by bonsairobo** [ron-rs/ron#238]
Pretty self-explanatory. I tried to use "[[1, 0, 0], [0, 1, 0], [0, 0, 1]]" for a `[[i32; 3]; 3]`, but the parser gives an `ExpectedArray` error. It worked once I changed it to "((1, 0, 0), (0, 1, 0), (0, 0, 1))".

**Comment by kvark** [comment]
The square brackets are used for variable size arrays, e.g. `Vec`. Fixed-size arrays are unfortunately treated differently - this is imposed by Serde, I don't know what we can to do here.
Could you quote the documentation bit you are referring to?

**Comment by bonsairobo** [comment]
"The new format uses (..) brackets for heterogeneous structures (classes), while preserving the {..} for maps, and [..] for homogeneous structures (arrays). This distinction allows us to solve the biggest problem with JSON."

This is in the github README.

**Comment by kvark** [comment]
We should at least change "arrays" to "dynamic arrays"

**Comment by kvark** [comment]
comment
