### ISSUE TITLE
Pretty array formatting broken in 0.6.0

### ISSUE THREAD

**Issue by cart** [ron-rs/ron#240]
0.5.1
```
array: [
    (),
    (),
    (),
],
```

0.6.0
```
array: [

    (),
    (),
    (),    ],
```

**Comment by kvark** [comment]
@Plecra would you be able to see if this is a regression from #206?

**Comment by Plecra** [comment]
Ah, it certainly is - it's actually two separate mistakes. A test should be added and these lines fixed:

https://github.com/ron-rs/ron/blob/42b0f6247183f6ddcd93ba1cd1354654ad9de30e/src/ser/mod.rs#L613-L625

This needs to be moved to the `Rest` block

https://github.com/ron-rs/ron/blob/42b0f6247183f6ddcd93ba1cd1354654ad9de30e/src/ser/mod.rs#L639-L643

, and a newline needs to be emitted here

**Comment by kvark** [comment]
Great, thank you for looking into it promptly, @Plecra! Would you be able to turn this into a PR?
