### ISSUE TITLE
Nested comments

### ISSUE THREAD

**Issue by Boscop** [ron-rs/ron#245]
Please allow nested comments like /* foo /* bar */ baz */ in RON files.

**Comment by kvark** [comment]
This is already supported. If not, please file a bug and provide an example.

**Comment by Boscop** [comment]
@kvark Ah, then it's only in the Sublime Text package that doesn't hightlight nested comments correctly.

**Comment by kvark** [comment]
Yeah, I noticed that too. Would love to get that fixed in the plugin!
