### ISSUE TITLE
Suggestion: use a more idiomatic builder pattern in PrettyConfig

### ISSUE THREAD

**Issue by allsey87** [ron-rs/ron#249]
Just wanted to point out that I think the use of `with_xxx` methods that take ownership of an instance of `ron::ser::PrettyConfig` and return a modified version of it is not the most idiomatic way of doing things in Rust. As I understand, generally the `with_xxx` methods should create new instances and not modify existing ones...

**Comment by kvark** [comment]
Thank you for filing this!
> with_xxx methods should create new instances and not modify existing ones

Why? The existing ones are consumed anyway. What's the harm in modifying them?

**Comment by allsey87** [comment]
There is no real harm here, it is just a bit unusual when contrasted against other libraries in the Rust ecosystem. For example `Vec::with_capacity` does not modify an existing vector, it creates a new one. The same goes for `HashMap::with_hasher` and `HashMap::with_capacity_and_hasher`. The obvious flaw here is that this doesn't scale well, however, the solution is normally then to use the builder pattern. Taking an example from the [clap](https://docs.rs/clap/2.33.1/clap/) create, they use `Arg::with_name(&str)` and then further configure the returned instance using `.short(&str)`, `.long(&str)`, and `.help(&str)`.

None of this is strictly necessary to follow, but I personally really appreciate these idiomatic coding styles that have emerged since it makes Rust code easier to read and write. Food for thought :)

**Comment by kvark** [comment]
> The obvious flaw here is that this doesn't scale well

This isn't obvious just yet. I'd like to see what may go wrong with the approach we have, in order to motivate changing it.

Currently, since every builder method affects exactly 1 field, and that field is being mutated by the implementation, I don't see what can go wrong. Seems very straightforward and non-prone to errors.

**Comment by kvark** [comment]
Idiomatic code in Rust doesn't appear out of nowhere, it emerges from many use patters, and it's goal is to help code producers and consumers. So in most, if not all, cases where there is an "idiomatic" way, it's based on very practical concerns, they just don't necessarily show themselves as obvious.

In this case, I'm trying to see what practical benefits would this change get us, and so far I wasn't able to see any.

Also, `Vec::with_capacity` and `HashMap::with_capacity_and_hasher` are not relevant, they are just constructors, they aren't using the builder pattern.

The `clap` code has a different kind of builder, it's not chain-able (functions don't return anything). It's hardly more idiomatic.

**Comment by allsey87** [comment]
I agree with most of what you are saying. To be clear, the issue is not with how you construct or configure your objects but rather how you name the functions that do this.

The `with_` prefix signals to other programmers that this is a static method that produces a type of `Self`.

**Comment by kvark** [comment]
Sure, we can rename these methods. Any ideas on what would be a better prefix?

**Comment by allsey87** [comment]
I think the idiomatic way is actually not to use a prefix for this. For example:
```Rust
let pc = 
   PrettyConfig::new()
      .depth_limit(4)
      .indentor("\t");
```

**Comment by SirWindfield** [comment]
If this is still wanted I can do a PR and rename the methods :)

**Comment by kvark** [comment]
@SirWindfield you are welcome to!
