### ISSUE TITLE
Avoiding duplicate parens around enum variant members (related to newtype-wrapping)

### ISSUE THREAD

**Issue by Boscop** [ron-rs/ron#250]
E.g. if I have this:
```rust
#[derive(Deserialize)]
pub enum Foo {
	A(A),
	B(f32),
}

#[derive(Deserialize)]
pub struct A {
	pub b: u8,
}
```
in RON I have to write `A(( b: 42 ))`. 
It would be preferable to be able to just write `A( b: 42 )` (similar to the already implemented [newtype-wrapping](https://github.com/ron-rs/ron/pull/72)), but currently this gives an error.

**Comment by kvark** [comment]
I agree it would look better, and I've been annoyed by this a bit too. I am concerned though about the consistency of the syntax if we try to bend it though. Worth looking at!
