### ISSUE TITLE
Return error when additional/unknown fields are present in RON file

### ISSUE THREAD

**Issue by Boscop** [ron-rs/ron#251]
I've been bitten several times by the fact that the RON parser doesn't return an error when fields are present that are not in the struct.
(In most cases the mistake when editing the RON file was that the field should have been written in another scope nearby.)
Please make it an error to have additional fields in the RON file.

If that's not possible/desired, please at least add an optional way to enable this.
E.g. `#![disable(unused_fields)]` or `#![deny(unknown_fields)]`

**Comment by kvark** [comment]
If it's something we control, as opposed to Serde, then I'm fully with you that we should return an error!
Otherwise, it will need to be resolved upstream with Serde.

**Comment by SirWindfield** [comment]
I am really not that familiar with `serde` internals, but I know that serde provides the [deny_unknown_fields](https://serde.rs/container-attrs.html#deny_unknown_fields) container attribute. By default, unknown fields should be ignored and adding that attribute should result in parsing errors.

**Comment by kvark** [comment]
That's helpful, thanks @SirWindfield !
@Boscop should we close this?

**Comment by Boscop** [comment]
Thanks :)

**Comment by juntyr** [comment]
> Adding
> 
> ```
> #[serde(deny_unknown_fields)]
> ```
> 
> ... above a struct works well.
> 
> Let's add this to the RON documentation. :)

Good idea - do you want to open a PR for that @xpe?
