### ISSUE TITLE
typetag: apparent cross-crate incompatibility wrecks enums

### ISSUE THREAD

**Issue by workingjubilee** [ron-rs/ron#254]
( side note:  I '""love""" the new Github UI. )

When combined with [typetag], the result does not appear to successfully parse RON enums -> serde enums -> trait objects, as I would expect. I am currently still trying to narrow the exact problem down, so I am not definitively sure whether it is an issue in this crate or the other one. Apologies. Currently in-progress.

[typetag]: https://lib.rs/crates/typetag

**Comment by MomoLangenstein** [comment]
@workingjubilee Could you perhaps send me a failing example (I haven't used `typetag` before). Thanks!

**Comment by Yarwin** [comment]
Side note (since it's hard to find any working example): I tried RON with typetags and it was working correctly:

```rust
#[derive(Deserialize, Serialize, Debug)]
pub struct Component1 {
    value: f32,
    value_2: f32
}

#[derive(Deserialize, Serialize, Debug)]
pub struct Component2 {
    value: f32,
}

#[typetag::serde(tag = "type")]
trait MyTrait: Debug {}

#[typetag::serde]
impl MyTrait for Component1 {}

#[typetag::serde]
impl MyTrait for Component2 {}


#[derive(Deserialize, Serialize, Debug)]
pub struct EntityConfig {
    pub name: String,
    pub components: Vec<Box<dyn MyTrait>>
}

fn main() {
    let file = fs::File::open("./data.ron").unwrap();
    let mut entity_config: EntityConfig = ron::de::from_reader(file).unwrap();
    assert_eq!(entity_config.components.len(), 2);
    println!("{:#?}", entity_config.components);
}
```

data.ron:
```rust
EntityConfig(
    name: "some name",
    components: [
        {
            "type": "Component1",
            "value": 22,
            "value_2": 35.0
        },
        {
            "type": "Component2",
            "value": 3.14,
        },
    ]
)
```

Obviously being able to write 
```rust
EntityConfig(
    name: "some name",
    components: [
        Component1(
            value: 22,
            value_2: 35.0
        ),
        Component2(
            value: 3.14
        )
    ]
)
```

**Comment by juntyr** [comment]
I'll close this once I've added a test to ensure this remains working (and I hope I'll remember it with the new label)
