### ISSUE TITLE
MSRV

### ISSUE THREAD

**Issue by SirWindfield** [ron-rs/ron#256]
Is there any particular MSRV (minimal supported Rust version) you guys try to aim for? There are some coding patterns that are actually outdated on stable in the code base that I'd like to fix :).

If so, what version is it?

**Comment by kvark** [comment]
We'd want to have MSRV defined, tracked, and tested.
It should be no higher than whatever Debian allows.

**Comment by SirWindfield** [comment]
Debian LTS is `Stretch` right now, which has, as of today, Rust version 1.34.2 available.
The newest Debian has 1.43.0 available.

It's your call :)

**Comment by SirWindfield** [comment]
Using the LTS version would pin us down for two years to 1.34.2 though, which is imo too long

**Comment by kvark** [comment]
Sounds good, let's start with 1.41.0
Thank you for investigating this!

**Comment by torkleyy** [comment]
RON is tested against 1.34 right now:

https://github.com/ron-rs/ron/blob/5947067d1505bb785f992d22c156d08d7e0ee302/.github/workflows/ci.yaml#L12
