### ISSUE TITLE
Floats can be serialized as ints

### ISSUE THREAD

**Issue by DomWilliams0** [ron-rs/ron#263]
I've noticed that float serialization uses the display `{}` formatting for floats, which annoyingly causes "round" floats (1.0, 2.0, etc) to be serialized as integers:

```rust
let a = Value::Number(Number::Float(Float::new(0.9)));
let b = Value::Number(Number::Float(Float::new(1.0)));

let a = ron::ser::to_string(&a).unwrap();
let b = ron::ser::to_string(&b).unwrap();

println!("{}", a); // 0.9
println!("{}", b); // 1
```
This doesn't look like intended behavior to me? If not it could be fixed by using debug `{:?}` formatting for floats instead.

**Comment by cart** [comment]
I recently added support for this in master via `PrettyConfig::decimal_floats`:
https://github.com/ron-rs/ron/blob/14173aecdc747b947d6a5119d2a3ed26d89ef3c5/src/ser/mod.rs#L81

**Comment by kvark** [comment]
@DomWilliams0 do you consider this resolved now?

**Comment by DomWilliams0** [comment]
@cart fantastic, I didn't notice that! Thanks.

@kvark yep, I'll close it.
