### ISSUE TITLE
Missing commas produce unhelpful errors with col/line 0

### ISSUE THREAD

**Issue by WaffleLapkin** [ron-rs/ron#265]
This code:
```rust
    #[derive(serde::Deserialize)]
    struct Test {
        a: i32,
        b: i32,
    }
    let string = r#"Test(
        a: 1 // <-- forgetten comma here
        b: 2
    )"#;

    ron::from_str::<Test>(string).unwrap();
```
Produces the following error:
```text
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: Message("missing field `b`"), position: Position { col: 0, line: 0 } }', src/main.rs:67:35
```

Which is really hard to understand because 
1. it says field `b` is missing but it doesn't
2. it doesn't say anything about commas
3. it points to `0, 0`

**Comment by kvark** [comment]
On a more general note, I was wondering if we could integrate https://github.com/brendanzab/codespan for proper error reporting.
