### ISSUE TITLE
Extension for declaring enums, and deserializing as enum repr

### ISSUE THREAD

**Issue by ratmice** [ron-rs/ron#268]
This is kind of a can of worms, and merely a first stab/rough draft at thinking about solutions,
but it did come up in some stuff I am working on.  Not sure whether its worth the added complexity given that most use cases don't actually run into anything like this.

I was thinking trying to work with graph data converted into Ron format from other formats.
Below is a simplified example, where the thing to note is that its using _enum values_ for vertices and edges...

```
Graph(
  vertices: {
      Foo: "Some",
      Bar: "random",
      Baz: "stuff"
  },
  edges: {
      "Foo -> Bar": (Foo, Bar),
      "Bar -> Baz": (Bar, Baz),
      "Baz -> Foo": (Baz, Foo),
  }
)
```

To decode this in a program, I then have to hard code into the program the actual enum.
and the program becomes specific to graphs over that set of vertices.
```
// bunch of derives... 
enum ID {
  Foo,
  Bar,
  Baz
}

struct Graph {
  vertices: HashMap<ID, String>,
  edges: HashMap<String, (ID, ID)>,
}
```

I was thinking it could be nice if you could specify the enum and repr _inside the ron file_,
Have the data checked internally as if it were enums, but deserializing to the repr value.

```
#![enable(enum_repr_declarations_deserialized_as_repr)]
#[repr(u8)]
enum ID {
  Foo,
  Bar,
  Baz
}

Graph(
  vertices: {
      Foo: "Some",
      Bar: "random",
      Baz: "stuff"
  },
  edges: {
      "Foo -> Bar": (Foo, Bar),
      "Bar -> Baz": (Bar, Baz),
      "Baz -> Foo": (Baz, Foo),
  }
)
```

Then modify the code as so:
```
struct Graph {
  vertices: HashMap<u8, String>,
  edges: HashMap<String, (u8, u8)>,
}
```

There are a number of questions about how such a thing works when serializing,
The only thing that comes to mind that seems feasible might be using a specialized deserialization/serialization methods that produce and consume serialization mapping from the repr into and out of the enum.

I've looked a bit and don't *think* i've missed anything which could do this sort of thing without an extension -- by all means let me know if otherwise.

**Comment by kvark** [comment]
Unless you have a very specific case where you know what vertices your graph has, it seems rather unfortunate to hardcode the enum variants in the code. Wouldn't it be simpler if the vertices where just strings?
```ron
Graph(
  vertices: {
      "Foo": "Some",
      "Bar": "random",
      "Baz": "stuff"
  },
  edges: {
      "Foo -> Bar": ("Foo", "Bar"),
      "Bar -> Baz": ("Bar", "Baz"),
      "Baz -> Foo": ("Baz", "Foo"),
  }
)
```

**Comment by ratmice** [comment]
I've slightly update the (2nd half of) the comment to hopefully better explain what I was spitballing.

What I don't like about strings here is two-fold, It doesn't check for typos like
`"Foo -> Bar": ("FOO","Bar"),`, and I still have to go and convert all the vertices into numeric indices or matrix coordinates anyways.

So if there were a way we could have types local to the Ron file, that decode as primitive types,
I would much rather see that.

**Comment by kvark** [comment]
I think I understand this better now. So on one hand, you don't want the Rust side to know about your vertices, it will just get a list of them. On the other side, you want a way for RON file itself to be consistent, i.e. don't just use random strings internally.

**Comment by ratmice** [comment]
Yes, exactly.  

Another issue that i've noticed is would only really work for unitary enum variants, such as the above (Rust has much the same issue IIRC with `as`, As such it wouldn't work with the general rust variants `enum { Foo(String) }` and the like. 

One thing is that when serializing it should probably involve an `impl<T> TryFrom<T> for DeclaredEnum<T>` where the other direction is an infallible `From<T> for DeclaredEnum<T>` or `Into`.  

Anyhow -- at this stage just looking for feedback positive/negative/alternative.  Or if you think this is deserving of a custom format (Staying as close to Ron as possible).  E.g. with a custom format I could just introduce an alternative to `enum`, such as `index {Foo, Bar, Baz}` which can only contain unitary variants, and it wouldn't have to add any additional complexity to Ron...

**Comment by kvark** [comment]
It sounds useful. The question is - what would it take to implement this.

**Comment by ratmice** [comment]
I've implemented an initial stab at parsing, and some tests, and noted limitations i've encountered while implementing in the [extension docs](https://github.com/ratmice/ron/blob/enum_repr/docs/extensions.md) 

**deserialization** is currently returning **stubbed out** values.
Want to get rid egregious stuff before I submit a PR however.

**Comment by ratmice** [comment]
So, I believe the consensus is that this needs to be done via some sort of pre-parsing, which RON is oblivious to and shouldn't involve RON itself.

It adds to the added complexity a large reliance on rusts syntax, and probably not a good fit for RON since typical use cases won't actually benefit from this.
