### ISSUE TITLE
Change intellij link to point to the group's repo

### ISSUE THREAD

**Issue by JonahHenriksson** [ron-rs/ron#273]
A quick change in README.md, change the free intellij link so it points to the repo I transferred to the group. I don't have access, and it's not worth a pull request, so I thought I would just mention it.

**Comment by kvark** [comment]
Thank you, fixed now!

**Comment by ozkriff** [comment]
maybe it's worth removing a link to https://vultix.github.io/intellij-ron-plugin/ from the readme? as far as i can tell, it's not usable and not supported now.

**Comment by kvark** [comment]
Fixed in #274
