### ISSUE TITLE
Usage examples

### ISSUE THREAD

**Issue by mfdorst** [ron-rs/ron#280]
I can't find any usage examples of RON and so I have no idea how to actually use it in my code. What do I import? Do I use `serde` in conjunction with `ron`, or just `ron`? If some code examples could be added to the README and also the documentation, that would go a long way to get people started quicker.

**Comment by johnoneil** [comment]
@mfdorst I've found the example code in the repo `example` directory helpful, but only at a basic level.
The examples leave many dark areas I still have to subsequently research. For example, does the .ron format support de-serializing arrays or vectors?

**Comment by kvark** [comment]
As @johnoneil said, there is an example. RON crate is a serde-based serialization library, so it's used just like any other serde serializer. I agree that the example should feature vectors/arrays. A PR would help!

**Comment by kvark** [comment]
Fixed by #283
