### ISSUE TITLE
Confusing error msg when file is in UTF-16

### ISSUE THREAD

**Issue by Boscop** [ron-rs/ron#282]
It took me some time to figure out why parsing failed for a file that was syntactically correct.

> Error: 1:1: Expected struct

![image](https://user-images.githubusercontent.com/535593/99546149-6ded7f80-29b6-11eb-83f9-b4f5c09b5cf7.png)

The first 2 bytes were FF FE, which means it was in UTF-16 encoding for some reason.
https://en.wikipedia.org/wiki/Byte_order_mark#UTF-16

I fixed it for my case by doing:

```rust
use encoding_rs_io::DecodeReaderBytes;

pub fn load_from_ron_file<T: DeserializeOwned>(path: &Path) -> Result<T> {
	Ok(ron::de::from_reader(DecodeReaderBytes::new(BufReader::new(File::open(path)?)))?)
}
```

But maybe ron-rs should give a better error? Or is it too high up the food chain (regarding decoding)?

**Comment by kvark** [comment]
Looks like it *can* be handled by user code. It belongs to how I/O is done more than parsing or anything, so seems largely out of scope for ron.
