### ISSUE TITLE
Large u64 values overflow as negative i64

### ISSUE THREAD

**Issue by m-ou-se** [ron-rs/ron#285]
Large u64 values that do not fit in a i64 should be stored as f64, by this code:

https://github.com/ron-rs/ron/blob/5e0f3c5e00732c43b457ff10ffb1605321a7b9d0/src/value.rs#L255-L261

However, `i as i64 as u64 == i` is always true. A value that doesn't fit in a a`i64` just overflows in both casts, and results in the same value.

This results in large u64 values being silently converted to large negative i64 values.

**Comment by torkleyy** [comment]
Hahaha no way I wrote that :sweat_smile:
