### ISSUE TITLE
No space after semicolons & comma after struct fields is not "pretty"

### ISSUE THREAD

**Issue by Boscop** [ron-rs/ron#290]
Consider this:
```rust
        [
            Some((
                asset: Misc(Buffer),
                sampler: (filter:mipmap,wrap:clamp,vflip:true), // should have spaces after semicolons & commas
            )),// [0]
            None,// [1]
            None,// [2]
            Some((
                asset: Misc(Stream),
                sampler: (filter:linear,wrap:clamp,vflip:true),
            )),
        ],
```

https://docs.rs/ron/0.6.2/ron/ser/struct.PrettyConfig.html#structfield.depth_limit

The types after this depth should still follow normal formatting guidelines like having spaces after semicolons & commas.

> depth_limit: usize
> Limit the pretty-ness up to the given depth.

What does this even mean? That everything after that level is not pretty-printed?
I use `.with_depth_limit(4)` but I don't want everything beyond that depth to not be pretty,
I just want to limit the depth for expanding types to multiple lines.

Actually what I'd **really** want is some `max_width` limit like in rustfmt to say that types should be written on one line unless they go over that limit. I thought that's what the depth limit is for, but apprently not.
Can you please add something like `max_width`? :)

**Comment by kvark** [comment]
> What does this even mean? 

I think having spaces after commas would still be nice there. But the idea was to stop breaking the lines, at least.

`max_width` is not something I needed personally, but if you want to contribute this, I can believe it's going to be useful to some.

**Comment by kvark** [comment]
comment

**Comment by MomoLangenstein** [comment]
@Boscop Have #344 and #349 solved your issue?
