### ISSUE TITLE
Consider EKON

### ISSUE THREAD

**Issue by Himujjal** [ron-rs/ron#292]
> Why not XXX?

>   if you know a better format, tell me!
 
Checkout [EKON](https://github.com/Himujjal/ekon). Its the "The End" to markup languages. By the way, nice work!

**Comment by kvark** [comment]
Thank you for filing! Here is my first reaction.

Objects are nice.
Strings without quotes are concerning, even if it's just for simple strings. Too easy to mistake a string for an identifier this way. You already have to have the "reserved words" just to disambiguate some of these cases.

> Backwards Compatibility with JSON

So it's either suffering from the same problems as JSON, or from the blownup scope and identity, like YAML.

Overall, amazing work, and thank you for sharing!

**Comment by Himujjal** [comment]
EKON doesn't have identifiers. Only literals. `null`, `true`, `false` and numbers. KISS principle there.
Strings without quotes makes up for the readability part. There are reserved characters and words.

JSON has its fair share of problems. Readability being one. YAML is unnecessarily complex with tab-based spacing (which sucks IMHO). My aim was to target programmers and non-programmers alike. So that config files are super-easy to write. 

Ron is an interesting format and a great work by the way. I like the fact that it supports serde out of the box. Good work!
