### ISSUE TITLE
How do I encode to a file?

### ISSUE THREAD

**Issue by Septias** [ron-rs/ron#293]
There is a nice example about how to decode from a file but the counterpart on how to encode to a file is missing. I think need one or two more steps but I don't know what to do. Can someone tell me?
```rust
let pretty = PrettyConfig::new().with_separate_tuple_members(true).with_enumerate_arrays(true);
let writer = File::create("structure.ron").expect("unable to create save-file");
let s = to_writer_pretty(writer, &ilias_tree, pretty).unwrap();
```

**Comment by Septias** [comment]
It works this way, but it doesn't look like it's the preferred way.
```rust
let pretty = PrettyConfig::new().with_separate_tuple_members(true).with_enumerate_arrays(true);
let mut writer = File::create("structure.ron").expect("unable to create save-file");
let s = to_string_pretty(&ilias_tree, pretty).unwrap();
writer.write_all(s.as_bytes());
```

**Comment by kvark** [comment]
How about using [to_writer_pretty](https://docs.rs/ron/0.6.4/ron/ser/fn.to_writer_pretty.html) and pointing it to the file?

**Comment by Septias** [comment]
I tried but that didn't work.
But I got it working another way so I'll close it for now
