### ISSUE TITLE
Pretty format option for serialising `None` option variants

### ISSUE THREAD

**Issue by Iselk** [ron-rs/ron#300]
Hi. Loving the format so far!

I however wondered if we can have a feature to exclude serialising `None` `Option` variants.

I think the option should be in `ron::ser::PrettyConfig`.

It might reduce clarity in the output in some cases, therefore it should only be optional.

I'd gladly help, and if you think this is a good idea, I could do all the work myself.

**Comment by kvark** [comment]
I wonder if this needs to be solved at RON level at all.
Serde has this `skip_serializing_if = "Option::is_none"`, which allows you to control it on field-by-field basis, which is already more powerful (although more verbose), and doesn't require anything from our side.
Perhaps, an issue needs to be filed to Serde asking for a way to say "skip serializing any field that has a default deserializer, and the value is default"?

**Comment by jonasbb** [comment]
@iselk If you have many `Option` fields you can reduce the boilerplate code by using the [`serde_with::skip_serializing_none!`](https://docs.rs/serde_with/1.6.4/serde_with/attr.skip_serializing_none.html) macro.

**Comment by Iselk** [comment]
@jonasbb Thanks!
