### ISSUE TITLE
Another format - na

### ISSUE THREAD

**Issue by joakim** [ron-rs/ron#305]
The readme asked for better formats.

I won't claim mine is a better format, but [na](https://github.com/kesh-lang/na) does have some similarities to RON.

One of the examples from the readme, in na:

```lua
GameConfig( -- optional struct name
    window_size: (800, 600)
    window_title: 'PAC-MAN'
    fullscreen: false
    
    mouse_sensitivity: 1.4
    key_bindings: {
        'up': Up
        'down': Down
        'left': Left
        'right': Right
        
        -- Uncomment to enable WASD controls
        -- 'W': Up
        -- 'A': Down
        -- 'S': Left
        -- 'D': Right
    }
    
    difficulty_options: (
        start_difficulty: Easy
        adaptive: false
    )
)
```

Maybe this can serve as inspiration for further simplifying your syntax? Note how commas are optional when multiline.

**Comment by kvark** [comment]
Thank you for showing this! It looks quite similar.
From a cursory look, some of the differences are: whitespace-sensitivity, lack of native `enum` support.
I wasn't able to see if it supports arbitrary types in the key position of key/value pairs. I.e. this part of `na` documentation is concerning:
```
s-record: [ foo: 42, bar: true ]  -- resembles swift dictionary, elixir keyword list
c-record: { foo: 42, bar: true }  -- resembles javascript object, python dict, go map
```
It's concerning because in both cases the `foo` and `bar` are not strings. So it's either that all key/value pairs have to have keys as strings (which would be sad), or that there is some magic going on allowing strings to be unquoted (which is a misfeature in my eyes).

**Comment by joakim** [comment]
And thank you for returning feedback!

na does use significant whitespace, but it's opt-in. A colon followed by newline opens a multiline collection where brackets are omitted and indentation is significant. Otherwise, whitespace is ignored. Commas are optional whenever newline is used to separate items, but they are still supported. I have yet to write a parser for na, so I haven't tested these rules for edge cases.

Record keys can be identifiers, strings or numbers (for sparse arrays). How these are mapped to the target language is up to the parser. Languages supporting the types would keep them, others might convert them to strings or identifiers.

It's currently not possible to enforce a more restricted syntax, like disallowing strings/numbers as keys for your enums. However, I could take inspiration from RON extensions, and use hashbang to allow a variant to be specified:

    #!ron [enable(implicit_some)]

Parsers that support the variant would parse it as "na-ron" while others would still be able to parse it verbatim. Not that I intend to subsume RON :) It would be a very elegant way to extend na in general.

There's another difference as well. na lacks support for your Map, which allows any value as key, including other maps. na did use to have a Map type with the syntax `#(value: value)` (or `#{ value: value }`). I'm still debating whether to include that.

Having looked more closely at RON, I must say it's a very neat format! It's clear that we see things similarly. And I'll openly admit that I've found inspiration in its features.
