### ISSUE TITLE
Cannot deserialize a struct with two number fields

### ISSUE THREAD

**Issue by nthieu173** [ron-rs/ron#312]
I'm currently using ron 0.6.4 and serde 1.0.127. I'm meeting a strange error where fail to deserialize a struct with two number fields. This is a minimal example:
```
use ron;
use serde::Deserialize;

#[derive(Deserialize, Debug)]
pub struct Example {
    number: u32,
    big_number: u32,
}
fn main() {
    let content = "Example (
        number: 0,
        big_numer: 0,
    )";
    let result: Example = ron::from_str(&content).unwrap();
    println!("{:?}", result);
}
```
which gives the error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: Message("missing field `big_number`"), position: Position { line: 0, col: 0 } }', src/main.rs:13:51
```
This does not seems like expected behavior though I would be happy to be shown where I'm using it wrong. Thank you.

**Comment by toyboot4e** [comment]
This is typo!

>         big_numer: 0,

But yes RON error message is not so much helpful.

**Comment by nthieu173** [comment]
Thank you, it seems that it is a typo in my RON after all. the position indicated in the error message tripped me up a lot because I was initially trying to deserialize into a Vec, and  because *all* of my classes (in the Vec) had a typo, it always told me that it's missing a field at Position { line: 0, col: 0 }, which only had the square bracket.
