### ISSUE TITLE
Error building ron with current rust compiler

### ISSUE THREAD

**Issue by greg7mdp** [ron-rs/ron#332]
With a newly installed rust, both on windows and ubuntu, I have the following error when trying to build the current version of ron:
![image](https://user-images.githubusercontent.com/1496907/139555575-9416ab96-77a9-4009-9eca-18b1fac713a7.png)

**Comment by MomoLangenstein** [comment]
If you are building from inside `ron`‘s folder, you might be building with its minimum supported Rust version, 1.36.0. What helps me in that case is to follow `ron`‘s CI action and run
```shell
cargo update -p bitflags --precise 1.2.1
cargo update -p indexmap --precise 1.6.2
```

**Comment by torkleyy** [comment]
If you need to build with an old Rust version, yes, you will have to do what @MomoLangenstein posted.

However, if you can @greg7mdp, don't use the packaged Rust version on Ubuntu, but instead get Rust using https://rustup.rs/

**Comment by greg7mdp** [comment]
Sorry, I'm a rust beginner.
I have the latest version installed, but when I use cargo inside `ron` directory it switches back to 1.36.
Here it is on windows:

```
C:\greg\github>where cargo
C:\Users\Valued Customer\.cargo\bin\cargo.exe

C:\greg\github>cargo --version
cargo 1.56.0 (4ed5d137b 2021-10-04)

C:\greg\github>cd ron

C:\greg\github\ron>cargo clean

C:\greg\github\ron>cargo --version
cargo 1.36.0 (c4fcfb725 2019-05-15)

```

and if I remove the 1.36 toolchain cargo reinstalls it:

```
C:\greg\github\ron>rustup toolchain uninstall 1.36.0-x86_64-pc-windows-msvc
info: uninstalling toolchain '1.36.0-x86_64-pc-windows-msvc'
info: toolchain '1.36.0-x86_64-pc-windows-msvc' uninstalled

C:\greg\github\ron>cargo clean
info: syncing channel updates for '1.36.0-x86_64-pc-windows-msvc'
info: latest update on 2019-07-04, rust version 1.36.0 (a53f9df32 2019-07-03)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: installing component 'clippy'
info: installing component 'rust-docs'
info: installing component 'rust-std'
info: installing component 'rustc'
info: installing component 'rustfmt'
```

**Comment by greg7mdp** [comment]
Just switching to the `ron` dir changes the cargo version (here on ubuntu):
```
greg@greg-ava:~/github$ cargo --version
cargo 1.56.0 (4ed5d137b 2021-10-04)
greg@greg-ava:~/github$ cd ron
greg@greg-ava:~/github/ron$ cargo --version
cargo 1.36.0 (c4fcfb725 2019-05-15)
greg@greg-ava:~/github/ron$
```

**Comment by torkleyy** [comment]
Oh, I missed that you were building the RON repo itself - there is a `rust-toolchain` file which sets the Rust version to 1.36

**Comment by torkleyy** [comment]
Just delete it and you'll be on your default version

**Comment by greg7mdp** [comment]
I don't get it? Why ship with a file forcing a version that doesn't compile?

**Comment by torkleyy** [comment]
> Why ship with a file forcing a version that doesn't compile?

The version does compile once you updated your lock file. I'm not sure why exactly we set it in that file though - could probably be set somewhere else. We use that version because it's our minimum supported Rust version (MSRV).

**Comment by MomoLangenstein** [comment]
The commands I posted above perform this lock file update.

**Comment by MomoLangenstein** [comment]
Though I agree that it is a bit awkward to require this step for the MSRV.

**Comment by greg7mdp** [comment]
Yes, but anyone cloning the ron repo (like me) and trying to build it will fail, right?

**Comment by MomoLangenstein** [comment]
If you use RON as a dependency in another project, then it works (at least it always has for me). But if you build just RON from the repo (e.g. to contribute a new feature), then I think you are right and the enforced MSRV forces you to first pin the versions of those two rogue dependencies.

**Comment by greg7mdp** [comment]
Thanks, I'll close the issue, but I still think that ideally the repo should also build by itself without changes, or if some extra steps are required, they should at least be documented in the README.
