### ISSUE TITLE
Revert #340

### ISSUE THREAD

**Issue by torkleyy** [ron-rs/ron#347]
The bitflags version cannot be locked as discussed after the merge of #340 

Thank you @Imberflur for raising awareness to this.

**Comment by Imberflur** [comment]
Np :slightly_smiling_face: 

The dubious nature of whether MSRV bumps count as semver breakage combined with cargo's forced unification of semver compatible versions is somewhat unfortunate here.

Hopefully future changes mentioned here https://github.com/rust-lang/rfcs/blob/master/text/2495-min-rust-version.md#future-work-and-extensions will allow cargo to not select newer versions of the crate when targeting a specific rust version.

Another alternative is creating a fork of bitflags, if its duplication in the dependency tree isn't a concern. Although the ability to deduplicate it when they are actually matching would be lost, so making cargo smart enough to work with MSRVs would be ideal.

**Comment by kvark** [comment]
fwiw, we recently stumbled upon a similar problem in wgpu (not the first time...), and finally decided to adopt a policy of "MSRV bumps = breaking change". This is enforced on CI by the fact we only test on MSRV and Nightly.
