### ISSUE TITLE
Don't allow struct name for unit

### ISSUE THREAD

**Issue by torkleyy** [ron-rs/ron#35]
I think allowing that (as we currently do) is confusing; it provides no extra information, but makes it ambiguous whether it is a unit or an enum variant.

**Comment by kvark** [comment]
We have ambiguity regardless. `()` can be a unit struct or just a unit.
What we have now is at least consistent: in all cases the struct name is optional.
Besides, I don't consider unit structs a strong use case to bend for.

**Comment by torkleyy** [comment]
Okay, fair.
