### ISSUE TITLE
Release 0.7.1 patch

### ISSUE THREAD

**Issue by kvark** [ron-rs/ron#365]
We need #335 to land on crates. There may potentially be other things that could be included.
@MomoLangenstein or @torkleyy - would you be interested in driving the patch release?

**Comment by MomoLangenstein** [comment]
@kvark I'd be very happy to work on the release. As I haven't created and uploaded a release before, I might need some brief guidance.

I think an updated version of #334 should also be included (otherwise we'd move the `struct_names` option to `PrettyConfig` just to move it again in the next update). Since there hasn't been any progress on that PR, I could take care of rebasing its changes on the current main branch and moving the option to `Options`.

#363 would be a very small change that could be included / closed as well.

**Comment by MomoLangenstein** [comment]
Edit: I had another think about #334 and at least for me I'm still not sure what the correct way there is. To get 0.7.1 to land quickly, it might be easier to just skip it and potentially move the `struct_names` config later.

I think it is correct that `struct_names` does more than just make the RON prettier (but so does `decimal_floats`, just to a lesser extent). Moving it to `Options`, however, also doesn't feel quite right as it only affects the `Serializer` so far. We could introduce a similar option for the `Deserializer` to enforce including struct names if enabled. Another option would be to go with the `_advanced` function pattern, but add new extensible config structs (like `PrettyConfig`) for both the `Serializer` and `Deserializer`, to allow them to more easily evolve should more options be needed in the future.

**Comment by kvark** [comment]
Thank you for helping!

We'd need to summon @torkleyy about process here, since they [convinced me to change](https://matrix.to/#/!jlooIrYHEoEvaAyVet:matrix.org/$xxmqztvgd-6t9RNuHacCiAL35ZzjT3Kbn9gNNLju-eI?via=matrix.org) the release/contribution workflow some time ago relative to what I do for all other projects, which resulted in #327 .

In other projects we'd just back-port some of the commits onto v0.7 branch and publish a patch from there.

**Comment by MomoLangenstein** [comment]
Yes, that would work as well

**Comment by kvark** [comment]
Yeah, we'll be doing a version churn, causing downstream to diverge in the used RON versions and produce duplicates in the vendored trees. This is quite unfortunate. Are you sure the simplified workflow is worth it?

**Comment by torkleyy** [comment]
Well, I don't think many libraries should be using RON, so I don't expect RON to be deep in a dependency tree.

**Comment by kvark** [comment]
There is quite a few libraries - https://crates.io/crates/ron/reverse_dependencies
Notably: wgpu, naga, specs, egui, bevy stuff, amethyst stuff, etc

**Comment by torkleyy** [comment]
Alright, then how about we cherry-pick the necessary fixes onto a v0.7 branch, release 0.7.1 and release master as 0.8.0?

**Comment by kvark** [comment]
Why do we need to release master as 0.8 now? Is there any feature users need today that wouldn't be published in 0.7.1?

**Comment by torkleyy** [comment]
Fixed by #382
