### ISSUE TITLE
a way to enable extention use in the parser instead of the document itself

### ISSUE THREAD

**Issue by autumnblazey** [ron-rs/ron#375]
currently you have to put something like `#![enable(implicit_some)]` in the beginning of every single ron document that you need to have an extention enabled in. Is there a way for this to be passed to `from_str` (or an alternative deserialisation API) instead of inside the document itself?

My use case for this is I need to create a lot of ron files and I know I would want all of them to have `implicit_some` enabled, and I think it would be less hassle to somehow enable this in the parser itself instead of in the individual documents.

An idea on how I this could be done is maybe have a chainable builder API or similar, so that I could build a reusable parser instance with the extentions enabled stored in them?

**Comment by MomoLangenstein** [comment]
This feature fortunately already exists, but has unfortunately not been released yet (but you can use it if you set `ron` as a git dependency). In #343 we added the `Options` builder struct. You can use
```rust
use ron::{Options, extensions::Extensions};

Options::default()
    .with_default_extensions(Extensions::IMPLICIT_SOME)
    .from_str(“ron”)
```
to automatically set these extensions during deserialisation and avoid including them during serialisation. This is meant to be used for round trips where you can guarantee that both ends are controlled by you and are configured with the same set of implicit extensions.

I hope this helps (typed on a phone so might include typos in the code) :)

**Comment by autumnblazey** [comment]
thats alright, thank you so much for the help, it seems to work as expected!
