### ISSUE TITLE
Is there a way to use to_string with struct names

### ISSUE THREAD

**Issue by lukyxu** [ron-rs/ron#381]
When using the ron::ser::to_string() function, the struct names option for the Serializer is set to false. Is there a way to run the same function but with struct names set to true? Since the output field of the Serializer struct is private, I was unable to rewrite the function in my own crate.

**Comment by MomoLangenstein** [comment]
You can use `ron::ser::to_string_pretty(value, ron::ser::PrettyConfig::new().struct_names(true))`

**Comment by lukyxu** [comment]
I was looking for this but it wasn't in v1.7.0. I see this has been added recently. Thanks.

**Comment by MomoLangenstein** [comment]
I'm glad I could help you :)
