### ISSUE TITLE
Release 0.8

### ISSUE THREAD

**Issue by torkleyy** [ron-rs/ron#395]
Opening this issue to discuss the 0.8 release. @JuniperLangenstein are there any PRs that you think should be merged before a new release? IIRC #394 introduces breaking changes, is that something we should include?

* [x] Figure out if any open PR should be in 0.8 and list it here
  * [x] #378
  * [x] #394
* [x] Figure out if any open issues should be fixed for 0.8 and list them here
* [x] Complete PRs & issues
* [x] Create PR with changelog, `Cargo.toml` and `lib.rs` updated
* [x] Create GH Release (+ git tag)

**Comment by MomoLangenstein** [comment]
@torkleyy I think #378 and #394 should both be merged beforehand - I can work on those for a bit later today. When should `ron` do its next MSRV bump? What about #255 - I see you closed the associated PR - should we still add `from_value` and `to_value`? #357 is probably something for 0.9. At some point, someone should probably tackle #321 ... Can you think of anything else?

**Comment by MomoLangenstein** [comment]
Completed in [v0.8.0](https://github.com/ron-rs/ron/releases/tag/v0.8.0)
