### ISSUE TITLE
Split ron file

### ISSUE THREAD

**Issue by TornaxO7** [ron-rs/ron#408]
Hello! Is it possible to "include" other ron files to separate a `ron` file into different `ron` files?

**Comment by MomoLangenstein** [comment]
@TornaxO7 So far this is not possible. However, it could perhaps be added as an extension. What use case and what syntax to import another ron document were you thinking of? How would we discover the other included ron files (ron just takes the bytes of the document and has no idea that they e.g. came from a file)? Perhaps this would better work as a user-side preprocessing step …

**Comment by TornaxO7** [comment]
> What use case and what syntax to import another ron document were you thinking of?

[`leftwm`](https://github.com/leftwm/leftwm) is switching to `ron` at the moment and I could imagine myself to split my config into multiple files to group the settings like: `settings.ron`, `keybindings.ron`, `layout.ron`, `mouse.ron` etc.

I could imagine to have something like
```ron
# `curr` points to the directory where the current file is
use curr::keybinding.ron;

# `settings` is a directory so the path is `./settings/window_behaviour.ron`
use curr::settings::window_behaviour.ron;
```
And `use <...>` should then just parse the given files

**Comment by MomoLangenstein** [comment]
That’s exciting to hear!

So would it work something like:
```rust
Config(
  keybindings: use curr::keybindings.ron,
  window: use curr::settings::window_bahviour.ron,
)
```

Adding this to the central serde-focused parser itself would probably require a significant amount of work (especially since ron is currently not aware of where the document comes from). Hence, my intuition would be that this should perhaps be some preprocessing step, which would benefit if it could use some of ron’s structural parsing - perhaps @torkleyy’s ron reboot parser could help with that?

**Comment by TornaxO7** [comment]
So would it work something like:
```ron
Config(
  keybindings: use curr::keybindings.ron,
  window: use curr::settings::window_bahviour.ron,
)
```

Hm.... I think
```ron
Config(
  keybindings: use curr::keybindings,
  window: use curr::settings::window_bahviour,
)
```
(difference: No file extension) would be nicer to read (and write).

But yeah, it should basically replace the `use curr::keybindings` with the content of the `keybindings.ron` file.

Another idea, to stick even more to the rust-syntax, would be to use `use super::keybindings` instead of `use curr::keybindings`.

**Comment by MomoLangenstein** [comment]
@TornaxO7 Another question would be if splitting can also be supported for writing. Always writing some sub paths to specific file could be possible through a helper struct that mimics the original outer config struct but wraps some fields in some new `ExtractToRonUse` wrapper struct.

**Comment by torkleyy** [comment]
Previous discussion: https://github.com/ron-rs/ron/issues/11

**Comment by TornaxO7** [comment]
> Previous discussion: #11

Oh, good that you're pointing this out! Hm... looks like that this isn't a good idea...

**Comment by TornaxO7** [comment]
I'll close this issue then.

**Comment by d86leader** [comment]
Hello! I found this issue today, and I agree that it should be a job of a separate tool. And then I thought that it would be a fun challenge to make this tool! So here it is: https://github.com/d86leader/ron-hs/blob/develop-include/extra/ron-include/src/Main.hs#L44

Written in 1:08:33, he-he

**Comment by MomoLangenstein** [comment]
That’s awesome @d86leader!
