### ISSUE TITLE
Trailing comma in Some()

### ISSUE THREAD

**Issue by qiujiangkun** [ron-rs/ron#410]
I'm parsing result from `rustc -Z unpretty=ast`, which yields a customized format of ron.
My plan is to use regex and ron to parse the result.
Currently `Some(1,)` doesn't work.  
```
Expected closing `)`
```
Is it supposed to work?

**Comment by MomoLangenstein** [comment]
@qiujiangkun Thank you for the bug report - this was indeed wrong and I've pushed a fix for it
