### ISSUE TITLE
Integration with oss-fuzz fuzzing service

### ISSUE THREAD

**Issue by manunio** [ron-rs/ron#414]
Hi, I would like to help integrate this project into [OSS-Fuzz](https://github.com/google/oss-fuzz).

- As an initial step for integration I have created this PR: https://github.com/google/oss-fuzz/pull/8676, it contains necessary logic from an OSS-Fuzz perspective to integrate ron.

- OSS-Fuzz is a free service run by Google that performs continuous fuzzing of important open source projects.

- As ron already have cargo-fuzz based fuzzing implemented, this makes it easily compatible with oss-fuzz out of box.

-  If you would like to integrate, the only thing I need is a list of email(s), it must be associated with a google account like 
gmail ([why?](https://google.github.io/oss-fuzz/faq/#why-do-you-require-a-google-account-for-authentication)). by doing that, the     provided email(s) will get access to the data produced by OSS-Fuzz, such as bug reports, coverage reports and more stats.

- As an alternative, if you don't have a google/gmail id, but still wish to integrate. I can add my mail id for time being and monitor bug/crashes.

- Notice the email(s) affiliated with the project will be public in the OSS-Fuzz repo, as they will be part of a configuration file.

**Comment by MomoLangenstein** [comment]
Thank you very much for creating the PR! I'd personally be inclined to support this. Perhaps we could create a new email account for the ron project that all maintainers have access to / that forwards to our private email addresses? @torkleyy and @kvark what are your thoughts?

**Comment by MomoLangenstein** [comment]
Ok, let's see what the others have to say :)

**Comment by torkleyy** [comment]
OSS-Fuzz seems great!

Would you prefer creating a separate email address? @MomoLangenstein

Personally I'm fine with using my individual email.

**Comment by MomoLangenstein** [comment]
> OSS-Fuzz seems great!
> 
> Would you prefer creating a separate email address? @MomoLangenstein
> 
> Personally I'm fine with using my individual email.

I'd like to definitely receive the emails, and I do not so far use gmail publicly. I can quickly create one if that option is easier/better than a team-associated email address.

**Comment by MomoLangenstein** [comment]
@manunio You can definitely add me with juniper.tyree@gmail.com .

**Comment by torkleyy** [comment]
@manunio Can you please also add torkleyy@gmail.com?
