### ISSUE TITLE
Pretty Print Multiline String

### ISSUE THREAD

**Issue by discord9** [ron-rs/ron#425]
Is it possible to add a config to `PrettyConfig` to allow `to_string_pretty` to print mulitline string as it is? For example, print
```
"a
b
c"
```
instead of `"a\nb\nc"`?

**Comment by MomoLangenstein** [comment]
@discord9 That's a great suggestion and I've taken a shot at implementing it. What do you think about #426?

**Comment by discord9** [comment]
> @discord9 That's a great suggestion and I've taken a shot at implementing it. What do you think about #426?

Now I can use `to_string_pretty` to format .ron file with long multiple line code block in it with ease, That's a great feature to have!
