### ISSUE TITLE
Minor grammer mistake in README

### ISSUE THREAD

**Issue by hgallagher1993** [ron-rs/ron#44]
> This distinction allows ....._(us / you?)_..... to solve the biggest problem with JSON.

**Comment by kvark** [comment]
As a non-native speaker, I don't see it being a grammar mistake. Could someone double-check?

**Comment by Xaeroxe** [comment]
Native speaker: should be "allows us to"

**Comment by torkleyy** [comment]
@Xaeroxe The current sentence is just "allows to solve [..]". Do we need to put an "us" in there?

**Comment by Xaeroxe** [comment]
Yes, at the very least it flows more naturally.  I opened #74
