### ISSUE TITLE
new release bumping `bitflags` dependency

### ISSUE THREAD

**Issue by extrawurst** [ron-rs/ron#469]
the last release is a while back and `bitflags` has seen a major version bump. dependencies like `ron` not being released with a version that supports building with `2.x` of bitlags keeps downstream dependencies from moving on. luckily its already on master and we only need a release. pretty please :)

**Comment by juntyr** [comment]
@kvark @torkleyy If you could give me the necessary rights to publish releases on crates.io, I could do so now and in the future

**Comment by extrawurst** [comment]
@juntyr any progress on getting publish rights? 
@kvark @torkleyy maybe there is a way to build a CD pipeline that allows publishing?

**Comment by juntyr** [comment]
@extrawurst Unfortunately I haven’t heard back from @torkleyy or @kvark yet. I hope I will soon :)

**Comment by juntyr** [comment]
https://github.com/ron-rs/ron/releases/tag/v0.8.1 has now been released to https://crates.io/crates/ron/0.8.1 and https://docs.rs/ron/0.8.1

**Comment by torkleyy** [comment]
Hey @juntyr sorry for the delay, you should have write access, right?

**Comment by juntyr** [comment]
> Hey @juntyr sorry for the delay, you should have write access, right?

Yes, I got access yesterday :)

And no worries about the delay - with now a third maintainer, it’ll be a lot easier to take breaks.
