### ISSUE TITLE
Implement deserialize_any

### ISSUE THREAD

**Issue by dtolnay** [ron-rs/ron#48]
It looks like RON is self-describing. It should be able to tell what type is in the data without relying on a Deserializer hint.

```rust
#[macro_use]
extern crate serde_derive;

extern crate ron;

#[derive(Deserialize, Debug)]
#[serde(untagged)]
enum Untagged {
    U8(u8),
    Bool(bool),
}

fn main() {
    println!("{}", ron::de::from_str::<u8>("99").unwrap());
    println!("{}", ron::de::from_str::<bool>("true").unwrap());

    // unhelpful panic :(
    ron::de::from_str::<Untagged>("true");
}
```

**Comment by torkleyy** [comment]
I started implementing that, but it turned out RON is not completely self-describing: There is no way to tell if it is an enum or a struct.

**Comment by dtolnay** [comment]
That shouldn't matter. JSON certainly doesn't distinguish between those right, and it is self-describing?

**Comment by torkleyy** [comment]
Okay, if that's the case I'll take a look at it later.
