### ISSUE TITLE
Consider Clojure

### ISSUE THREAD

**Issue by kvark** [ron-rs/ron#5]

**Comment by torpak** [comment]
Consider [Phlebas](https://en.wikipedia.org/wiki/Consider_Phlebas) 😉

**Comment by nogden** [comment]
More specifically [EDN](https://github.com/edn-format/edn)

Lots of effort has been put into this to ensure that it is applicable to any language.

**Comment by OvermindDL1** [comment]
I tended to like https://github.com/lightbend/config/blob/master/HOCON.md as a format personally, JSON but more useful as a config.  No clue about any existing clojure libraries (why is clojure support needed?).

**Comment by torkleyy** [comment]
Closing alternative issues and listing them in [the wiki page](https://github.com/ron-rs/ron/wiki/Alternative-formats).
