### ISSUE TITLE
Consider a slightly more concise format especially for arrays

### ISSUE THREAD

**Issue by pkphilip** [ron-rs/ron#50]
A more concise format for arrays can really help:

Instead of this:

```
Scene( // class name is optional
    materials: { // this is a map
        "metal": (
            reflectivity: 1.0,
        ),
        "plastic": (
            reflectivity: 0.5,
        ),
    },
    entities: [ // this is an array
        (
            name: "hero",
            material: "metal",
        ),
        (
            name: "monster",
            material: "plastic",
        ),
    ],
)
```

You can do something more concise:

```
Scene( // class name is optional
    materials: { // this is a map
        "metal": (
            reflectivity: 1.0,
        ),
        "plastic": (
            reflectivity: 0.5,
        ),
    },
    entities: [ 
       {"name", "material", }, //Use a map/tuple to define what fields will be there in each item in the array
       ( "hero", "metal"),  //the fields are presented in the same order with repeating column names
       ( "monster", "plastic",),
    ],
)
```

The first item in the array is actually an optional map which can be used to specify the column names. 

entities[0]["name"] will be "hero"
entities[0]["material"] will be "metal"

..and so on.

If the map defining the list of column names is not provided for an array, perhaps we can default to using integers for the column names indexed from 0.

Consider an example below without column names:
```
Scene( // class name is optional
    materials: { // this is a map
        "metal": (
            reflectivity: 1.0,
        ),
        "plastic": (
            reflectivity: 0.5,
        ),
    },
    entities: [       
       ( "hero", "metal"),  //the fields are presented in the same order with repeating column names
       ( "monster", "plastic",),
    ],
)
```
That is:
entities[0][0]  will be "hero"
entities[0][1]  will be "metal"
entities[1][0] will be "monster"
entities[1][1] will be plastic"

Using a map or a tuple in an array is definitely a bit ugly - perhaps an alternate syntax can be used but it does significantly reduce the overall size of the data especially if there are 100s (or more) items in an array.

It is also conceivable that the map describing the columns could be made much more sophisticated. 

Example:

Instead of:
```
  
"entities": [{"name", "material"},
     ("hero", "metal", ),
     ("monster", "plastic",),
 ],
```

The column definitions could be made much more detailed.

```
 "entities": [
            { "name": {
                 "type": "char",
                 "length": 10,
               },
              "material": {
                 "type": "char",
                 "length": 30,
              },
            },
          ("hero", "metal"),
          ("monster", "plastic"), 
  ]

```

**Comment by pkphilip** [comment]
Just to be clear, my essential point is that it would be useful to define the columns at one place and then use the relative position of the data in the fields to determine which field is for which column instead of repeating column names in each array item.

**Comment by kvark** [comment]
@pkphilip thank you for the suggestion!
I see it as an ergonomic improvement for arrays of structs at the cost of increased specification complexity. It doesn't appear to solve a problem that has no solutions or good workarounds: the user can just have an array of tuples in the first place instead of hacking the data format.

All in all, I don't think it's worth complicating the format for this specific case.

**Comment by torkleyy** [comment]
Fully agree with @kvark; RON should be simple (to read, write and in structure). It's goal is to look nice to the user and it is primarily written and edited by users. If you're worried about memory you should consider using a binary format / converting RON files to binary files at some point.

**Comment by pkphilip** [comment]
Got it

**Comment by torkleyy** [comment]
OK, I think this issue can be closed.
