### ISSUE TITLE
'Invalid type' when deserialising to ndarray types

### ISSUE THREAD

**Issue by Libbum** [ron-rs/ron#52]
Unsure if this is a problem here, or [ndarray](https://github.com/bluss/rust-ndarray), but considering I have no issues deserialising from json, yaml, messagepack etc to ndarray types, then I'm guessing here is a better place to start.

Using the [`Array3`](https://docs.rs/ndarray/0.10.4/ndarray/type.Array3.html) type (which implements `Deserialize` if you enable the `serde-1` feature) as an example, one can obtain the correct RON representation using `to_string`, but both `from_reader` and `from_string` yield an error.

A quick test:

```rust
let test = "(
    v: 1,
    dim: (1, 1, 1),
    data: [
        12.234,
    ],
)";

let conv: Array3<f64> = match ron::de::from_str(&test) {
    Ok(x) => x,
    Err(e) => {
        println!("{}", e);
    },
};
```
sees the following:

`invalid type: byte array, expected "v", "dim", or "data"`

Is this me configuring things incorrectly or has something been overlooked in this instance?

**Comment by torkleyy** [comment]
I'm pretty sure this is because other formats have the same representation
for strings and identifiers.

**Comment by Libbum** [comment]
Yeah, I think that's the case. 

It looks like the culprit in this particular instance is [this function](https://github.com/bluss/rust-ndarray/blob/master/src/array_serde.rs#L137,L146) in the ndarray `Deserialize` method. It matches on `&str` versions of these variables `v`, `dim` and `data`.

Although exactly how to remedy the problem is a little over my head. Is there a better way for ndarray to deserialise that I can suggest over there? Or can I force the ron parser to treat the data differently in some intermediate step?

**Comment by Boscop** [comment]
Maybe it should impl [visit_bytes()](https://docs.serde.rs/serde/de/trait.Visitor.html#method.visit_bytes) instead of `visit_str`?

**Comment by torkleyy** [comment]
@Boscop Yes, makes sense since the deserializer also calls this method. Don't have time to check that right now though.

**Comment by kvark** [comment]
Sounds like an upstream issue with `ndarray`. Anyone care to file a bug?

**Comment by Libbum** [comment]
Yep, I'll chase it. Just haven't had the time yet. Thanks for the help everyone.
