### ISSUE TITLE
Consider adding top-level attributes

### ISSUE THREAD

**Issue by torkleyy** [ron-rs/ron#69]
**Syntax:** `#![attribute_name]` (like in Rust)

After reading https://ozkriff.github.io/2017-12-01--devlog.html where @ozkriff said that his configs (https://raw.githubusercontent.com/ozkriff/zemeroth_assets/master/objects.ron) aren't looking very nice because of how RON handles newtypes, I thought about adding attributes which allow to configure RON for your needs. Not only would this allow for toggles like `#![unwrap_newtypes]`, but it could also be used to deal with new features. That way, we can just enforce that you need `#![feature_name]` to enable a RON feature, such that a parser without support for that feature can return a simple and understandable error.

**Comment by torkleyy** [comment]
@kvark Please tell me if you have concerns regarding the complexity, otherwise I'd like to implement this.

**Comment by kvark** [comment]
I agree that in Zemeroth case the newtype ergonomics could be better. I'm fine with adding the attributes as long as the default version of RON is simplest and most consistent of all its variations. So yes, please proceed if you want to take this @torkleyy 👍
