### ISSUE TITLE
Add hexadecimal numbers

### ISSUE THREAD

**Issue by ozkriff** [ron-rs/ron#76]
And maybe it's a good idea to add octal and binary (`0o...` and `0b...`) notations too.

**Comment by torkleyy** [comment]
Yep, @kvark mentioned this in a recent PR.

**Comment by kvark** [comment]
We happen to need this for gfx-warden as well. Even though, native support for `bitflags` would have been even better. Man can dream...

**Comment by torkleyy** [comment]
So I assume we use `0x` for hexadecimal and `0b` for binary?
