### ISSUE TITLE
Consider changing unicode escape sequence

### ISSUE THREAD

**Issue by torkleyy** [ron-rs/ron#83]
Currently, they look like `\u0007`. In Rust however, it is ``\u{0007}`.

@kvark Should we change that?

**Comment by kvark** [comment]
Let's follow Rust, unless there are any issues with this.

**Comment by SimonSapin** [comment]
For background: Unicode goes up to U+10FFFF (6 hex digits). The `\u{7}` syntax allows a variable number of digits, whereas `\u0007` is fixed to four. (`\u0007A` is U+0007 followed by a literal letter A.) Python for example has `\U` + eight hex digits, to represent code points that require more than four digits.

**Comment by torkleyy** [comment]
Done.
