### ISSUE TITLE
Date and time

### ISSUE THREAD

**Issue by kvark** [ron-rs/ron#91]
Interesting quote from a [reddit comment](https://www.reddit.com/r/rust/comments/7u4g4j/xi_an_editor_for_the_next_20_years_recurse_center/dtj8vzh/):
> No specification for how to handle dates or times. By convention, we've all kind of settled on ISO 8601, but JSON just gives us a string really. If you work with some older web services that offer JSON, particularly .NET-based ones, you're likely to get bit by this.

**Comment by moosingin3space** [comment]
Would this introduce a dependency on a particular date/time crate?

**Comment by torkleyy** [comment]
Depends on how we implement it :)

We can implement it ourselves or use e.g. chrono which

> [..] strictly adheres to ISO 8601

**Comment by Rhuagh** [comment]
Depends if you convert it to a specific data type or just validate a string format

**Comment by blanham** [comment]
@torkleyy +1 to using chrono, it's used by a ton of existing crates, so using it (and its data types) will
enable easy interop with existing crates.
