### ISSUE TITLE
Use in log-style formats

### ISSUE THREAD

**Issue by rsaarelm** [ron-rs/ron#99]
If the toplevel RON structure is an array, it needs matching [ and ] brackets in the beginning and end of the file, correct? What if I want to make an incremental log file that is only appended to and that parses as a valid RON file containing an array of log entry values after each write? I'd have to modify the existing file to remove the final ] before each new write.

There's [JSON Lines](http://jsonlines.org/) for the JSON version of an incremental file. Maybe RON could have some built-in support?

A very hacky and nasty approach would be to simply let you omit the final closing ] if the toplevel syntax element is an array.

**Comment by torkleyy** [comment]
> A very hacky and nasty approach would be to simply let you omit the final closing ] if the toplevel syntax element is an array.

Yeah, it's hacky and I don't think it's a good idea.

However, what I think would be generally useful is to have a way to insert just a few additional things without rewriting the original file. (I think there's something similar for TOML, something like `toml-edit`)

**Comment by torkleyy** [comment]
I think this should be solved by either

* appending a `]` on close or
* reading in comma separated lines yourself and passing line by line to RON

**Comment by torkleyy** [comment]
I really don't think RON will address this.
